#!/usr/bin/env python3
"""
FreshAir — put the current work in front of a model that has never seen this
conversation, and bring back what it says.

By default only two things leave: every instruction the human gave, and the
current state of the code. The hundred turns of agent reasoning in between are
withheld on purpose — a reviewer that reads those justifications first is
anchored by them, agrees, and tells you nothing you did not already believe.

Nothing here is summarized by the agent that is already stuck. This script reads
the session log itself.

Stdlib only. No install step.
"""

# `X | None` in a signature is evaluated at def time before 3.10; this defers
# every annotation so the script runs on whatever python the user already has.
from __future__ import annotations

import argparse
import base64
import concurrent.futures
import hashlib
import http.server
import json
import os
import re
import shutil
import secrets
import subprocess
import sys
import tempfile
import time
import time
import urllib.error
import urllib.parse
import urllib.request
import webbrowser
from datetime import datetime, timezone
from pathlib import Path

OPENROUTER_URL = "https://openrouter.ai/api/v1/chat/completions"

DEFAULT_MODELS = ["openai/gpt-5.1", "google/gemini-3-pro"]

# Locally installed vendor CLIs, each already signed in as the user. No API key
# changes hands and no transcript passes through a third party — the request
# goes straight from this machine to the vendor the user already pays.
#
# Every field here is overridable from .freshair.json under "backends", so a changed
# upstream flag is a config edit rather than a patch.
CLI_BACKENDS: dict[str, dict] = {
    "codex": {
        # `codex exec` already defaults to a read-only sandbox; say so explicitly
        # so a future default change cannot hand a reviewer write access.
        "cmd": ["codex", "exec", "--sandbox", "read-only",
                "--ask-for-approval", "never"],
        "tail": ["-"],               # `-` makes codex read the prompt from stdin
        "model_flag": "-m",
        "label": "Codex CLI (your ChatGPT login)",
        "vendor": "openai",
    },
    "gemini": {
        "cmd": ["gemini"],           # headless gemini reads a piped prompt
        "tail": [],
        "model_flag": "-m",
        "label": "Gemini CLI (your Google login)",
        "vendor": "google",
    },
    "claude": {
        "cmd": ["claude", "-p"],
        # Variadic, so it goes last — anything after it gets swallowed.
        "tail": ["--disallowed-tools", "Edit", "Write", "NotebookEdit", "Bash"],
        "model_flag": "--model",
        # Hands the repo back as a readable directory after we move the child
        # out of it. Backends without a known equivalent simply review the
        # payload, which is what the API backends do anyway.
        "dir_flag": "--add-dir",
        "label": "Claude Code CLI (your Anthropic login)",
        "vendor": "anthropic",
    },
}

# The vendor whose agent is running this skill. Asking it for a second opinion
# is the weakest version of this tool — same weights, same blind spots — so it
# is ranked last and called out at runtime when it is what we fall back to.
HOST_VENDOR = "anthropic" if os.environ.get("CLAUDECODE") else None

AUTO_ORDER = ["codex", "gemini", "claude"]

# Rough budget for the transcript we ship out, in characters.
DEFAULT_BUDGET = 140_000
TOOL_RESULT_CAP = 1_200
DIFF_CAP = 40_000

# A CLI backend writes its own session log. If it ever lands in the transcript
# we later read, the payload must be recognisable as ours rather than as
# something a human typed — otherwise each review feeds itself into the next.
FRESHAIR_MARKER = "freshair-review-request"
# Stamped on what we print, so a run whose output is captured as tool output
# does not come back as conversation on the next run.
OUTPUT_MARKER = "freshair-review-output"

MARKER_LINE = (
    f"<!-- {FRESHAIR_MARKER}: generated by FreshAir, not typed by a human -->\n"
)

# Payloads written before this marker existed, and before the tool was renamed.
# Transcripts polluted by an older version are still out there being read, so
# these have to keep matching for as long as those sessions do.
def is_own_payload(text: str) -> bool:
    """True if this text is FreshAir's own traffic from an earlier run.

    Two directions leak back into a session: the request we send a reviewer
    (which a CLI backend logs), and the review we print (which the host agent
    captures as tool output). Either one read back as conversation would make
    each run the input to the next.
    """
    return (FRESHAIR_MARKER in text
            or OUTPUT_MARKER in text
            or any(sig in text for sig in LEGACY_SIGNATURES))


LEGACY_SIGNATURES = (
    "wdyt-review-request",
    "You are an outside reviewer. You were NOT part of the conversation",
    "You are being handed a piece of work cold.",
)

SYSTEM_PROMPT_FULL = MARKER_LINE + """\
You are an outside reviewer. You were NOT part of the conversation you are about \
to read, and that is the entire reason you were called in.

The transcript below is a working session between a human and a coding agent. \
The agent has been in this conversation for a long time. It is now anchored: it \
keeps building on its own earlier decisions, treats its own assumptions as \
settled fact, and has stopped generating genuinely new options. The human called \
you because they suspect this has happened but cannot see it from inside.

You are reading the raw transcript, not a summary. Nobody has filtered it for \
you. That means the mistakes are still visible in it — an assumption that got \
made once and never questioned again, a requirement from the first message that \
quietly got dropped, a hard problem that got redefined into an easier one.

Rules:
- Judge the work, not the effort. Do not open with praise. Do not soften.
- Be specific. Point at the actual turn, decision, or line of code. "Consider \
edge cases" is worthless; "the retry loop added around turn 12 never resets \
`attempt`, so the backoff is wrong after the first failure" is worth reading.
- The agent's framing is not evidence. If the transcript takes something for \
granted, that is exactly the thing to poke.
- If they are actually on the right track, say so plainly and briefly, and spend \
your words on the sharpest remaining risk instead of manufacturing complaints.
{verify_rule}
"""

VERIFY_RULE_API = (
    "- You cannot run anything. If a claim in the transcript needs "
    "verification, say what you would run to check it."
)

VERIFY_RULE_CLI = (
    "- You are running in the repository this session is about. If a claim in "
    "the transcript needs checking, open the file and check it rather than "
    "taking the transcript's word for it. Do not modify anything."
)

SYSTEM_PROMPT_FRESH = MARKER_LINE + """\
You are being handed a piece of work cold.

You are deliberately NOT being shown how it got here. Somewhere behind this, a \
human and a coding agent went back and forth for a long time, and the agent \
ended up anchored on its own earlier decisions — treating its assumptions as \
settled and no longer generating new options. Showing you that reasoning would \
anchor you exactly the same way. So it was withheld.

You get two things and nothing else: what the human asked for, and what exists \
right now. Judge the second against the first, from scratch.

Rules:
- Reason forward from the goal, not backward from the code. The obvious \
approach to the stated problem may not be the approach that was taken — you \
are the only one left in this loop who can still see that.
- Do not assume a decision was considered and rejected for a good reason. If \
something looks wrong, the likeliest explanation is that nobody ever asked.
- Judge the work, not the effort. Do not open with praise. Do not soften.
- Be specific: name the file, the function, the line. "Consider edge cases" is \
worthless; "`fit_to_budget` drops the opening turns when the head alone \
exceeds the budget, so the original goal disappears exactly when it matters \
most" is worth reading.
- If the work does meet the goal, say so plainly and briefly, then spend your \
words on the sharpest remaining risk rather than manufacturing complaints.
{verify_rule}
"""

USER_TEMPLATE_FRESH = """\
{focus_block}\
===== THE GOAL — every instruction the human gave, verbatim =====
{goal}
===== END GOAL =====

{repo_block}{diff_block}{claim_block}
Answer in this structure, in {lang}:

## Verdict
One line, one of: KEEP GOING / ADJUST COURSE / STOP AND RETHINK — plus one \
sentence of why.

## Does this solve the stated problem
Hold what exists against the goal. What the goal asked for that is missing, and \
what is here that the goal never asked for.

## How you would have approached it
Knowing only the goal, what would you reach for? If it differs from what is \
here, say concretely what the difference buys — and if it does not differ, say \
that, because it is real information.

## Unexamined assumptions
What does this design take for granted? For each: why it might be wrong, and \
what it costs if it is.

## Concrete problems
Bugs, gaps, broken logic, missing cases. Cite file and line. Ordered by how \
much damage they do.

## What can be deleted
Anything here not earning its place? Say so even if it is most of the work.
"""

USER_TEMPLATE_FULL = """\
Read the session transcript below, then answer in the structure given at the end.

{focus_block}
{repo_block}
===== BEGIN SESSION TRANSCRIPT =====
{transcript}
===== END SESSION TRANSCRIPT =====
{diff_block}
Answer in this structure, in {lang}:

## Verdict
One line, one of: KEEP GOING / ADJUST COURSE / STOP AND RETHINK — plus one \
sentence of why.

## Drift
What did the human ask for in their earliest messages, and is that still what is \
being built? Quote the original ask. If it drifted, name the turn where it \
drifted.

## Unexamined assumptions
Things the transcript treats as settled that are not. For each: why it might be \
wrong, and what it would cost if it is.

## Concrete problems
Bugs, gaps, broken logic, missing cases. Cite where. Ordered by how much damage \
they do.

## The simpler path
Is there a materially simpler approach that was never considered? Is there a \
chunk of this that could just be deleted? Say so even if it means throwing away \
most of the work.

## If I started fresh
Two or three sentences: knowing only the original goal, how would you have \
approached this? If it is the same as what they did, say that — it is useful \
information.
"""


# --------------------------------------------------------------------------
# locating the transcript
# --------------------------------------------------------------------------

def mtime(path: Path) -> float:
    try:
        return path.stat().st_mtime
    except OSError:
        return 0.0


# --------------------------------------------------------------------------
# Codex sessions
#
# Codex files a "rollout" per session under
# $CODEX_HOME/sessions/YYYY/MM/DD/rollout-<timestamp>-<uuid>.jsonl, with the
# first line a session_meta carrying the directory the session ran in. Records
# come in two generations: newer Codex writes conversation turns as
# `response_item` entries, older ones as `event_msg`. Both are read, and the
# newer stream wins when a file has both, so turns are not counted twice.
# --------------------------------------------------------------------------

def codex_home() -> Path:
    return Path(os.environ.get("CODEX_HOME") or (Path.home() / ".codex"))


def codex_session_cwd(path: Path) -> str:
    """The directory a rollout was recorded in, from its session_meta header."""
    try:
        with path.open("r", encoding="utf-8", errors="replace") as fh:
            for _ in range(5):
                line = fh.readline()
                if not line:
                    break
                try:
                    rec = json.loads(line)
                except json.JSONDecodeError:
                    continue
                if rec.get("type") != "session_meta":
                    continue
                payload = rec.get("payload") or rec
                return str(payload.get("cwd") or "")
    except OSError:
        pass
    return ""


def codex_transcripts(cwd: Path) -> list[Path]:
    home = codex_home()
    files: list[Path] = []
    for root in (home / "sessions", home / "archived_sessions"):
        if root.is_dir():
            files.extend(root.rglob("rollout-*.jsonl"))
    files.sort(key=mtime, reverse=True)

    # Only sessions belonging to this project. A session started at the repo
    # root is still ours when we are invoked from a subdirectory.
    def norm(path: str) -> str:
        # Codex records whatever string it was started with; symlinked homes,
        # bind mounts and trailing slashes must not silently drop a session.
        try:
            return str(Path(path).expanduser().resolve())
        except (OSError, RuntimeError):
            return path.rstrip(os.sep)

    here = norm(str(cwd))
    owned = []
    for f in files:
        raw = codex_session_cwd(f)
        if not raw:
            continue
        session_cwd = norm(raw)
        if here == session_cwd or here.startswith(session_cwd + os.sep):
            owned.append(f)
    # (2) never hand back a review we ourselves spawned
    return [f for f in owned if not is_freshair_child(f)]


def codex_blocks_text(content) -> str:
    if isinstance(content, str):
        return content
    if not isinstance(content, list):
        return ""
    parts = []
    for block in content:
        if isinstance(block, str):
            parts.append(block)
        elif isinstance(block, dict):
            # input_text on user turns, output_text on assistant turns, and
            # plain text on anything written before that split existed.
            parts.append(block.get("text") or block.get("content") or "")
    return "\n".join(p for p in parts if p).strip()


def parse_codex(path: Path, keep_thinking: bool) -> list[dict]:
    items: list[dict] = []   # from response_item — the current format
    events: list[dict] = []  # from event_msg — the legacy one
    saw_item_message = False  # a tool call is not evidence of a conversation

    with path.open("r", encoding="utf-8", errors="replace") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            try:
                rec = json.loads(line)
            except json.JSONDecodeError:
                continue

            kind = rec.get("type")
            payload = rec.get("payload") or {}
            if not isinstance(payload, dict):
                continue
            ptype = payload.get("type")
            ts = rec.get("timestamp", "")

            if kind == "response_item":
                if ptype == "message":
                    role = payload.get("role")
                    if role == "developer":
                        continue  # harness scaffolding, not the conversation
                    text = codex_blocks_text(payload.get("content"))
                    role = "user" if role == "user" else "assistant"
                    if text.strip():
                        saw_item_message = True
                elif ptype == "function_call":
                    args = payload.get("arguments")
                    text = (f"[tool: {payload.get('name', 'tool')}] "
                            f"{clip(str(args), 400)}")
                    role = "assistant"
                elif ptype == "function_call_output":
                    out = payload.get("output")
                    if isinstance(out, dict):
                        out = out.get("content", out)
                    text = f"[tool result]\n{clip(str(out), TOOL_RESULT_CAP)}"
                    role = "tool"
                elif ptype == "reasoning":
                    if not keep_thinking:
                        continue
                    text = "[thinking] " + codex_blocks_text(
                        payload.get("summary") or payload.get("content"))
                    role = "assistant"
                else:
                    continue
                if text.strip():
                    items.append({"role": role, "text": text.strip(), "ts": ts})

            elif kind == "event_msg":
                if ptype == "user_message":
                    role = "user"
                elif ptype == "agent_message":
                    role = "assistant"
                else:
                    continue
                text = payload.get("message") or payload.get("text") or ""
                if text.strip():
                    events.append({"role": role, "text": text.strip(), "ts": ts})

    # A response_item stream carrying only tool records is not a conversation;
    # the legacy event stream may still hold the real one.
    turns = items if saw_item_message else events
    return [t for t in turns if not is_own_payload(t["text"])]


def project_dir_for(cwd: Path) -> Path:
    """Claude Code slugifies the cwd: every non-alphanumeric char becomes '-'."""
    slug = re.sub(r"[^a-zA-Z0-9]", "-", str(cwd))
    return Path.home() / ".claude" / "projects" / slug


def claude_transcripts(cwd: Path) -> list[Path]:
    pdir = project_dir_for(cwd)
    if not pdir.is_dir():
        return []
    files = sorted(pdir.glob("*.jsonl"), key=mtime, reverse=True)
    return [f for f in files if not is_freshair_child(f)]


SESSION_SOURCES = {
    "claude": {"find": claude_transcripts, "label": "Claude Code"},
    "codex": {"find": codex_transcripts, "label": "Codex"},
}


def find_transcript(explicit: str | None, cwd: Path, session_id: str | None = None,
                    source: str = "auto") -> tuple[Path, str]:
    """Locate the session to review, and say which host wrote it."""
    if explicit:
        path = Path(explicit).expanduser()
        if not path.is_file():
            die(f"transcript not found: {path}")
        if source == "auto":
            source = "codex" if path.name.startswith("rollout-") else "claude"
        return path, source

    # An exact session id beats any heuristic.
    session_id = (
        session_id
        or os.environ.get("CLAUDE_SESSION_ID")
        or os.environ.get("CLAUDE_CODE_SESSION_ID")
    )
    if session_id and source in ("auto", "claude"):
        candidate = project_dir_for(cwd) / f"{session_id}.jsonl"
        if candidate.is_file():
            return candidate, "claude"

    wanted = list(SESSION_SOURCES) if source == "auto" else [source]
    if source != "auto" and source not in SESSION_SOURCES:
        die(f"unknown session source {source!r}. Known: "
            + ", ".join(list(SESSION_SOURCES) + ["auto"]))

    # Newest wins: the session being appended to right now is the live one.
    best: tuple[float, Path, str] | None = None
    for name in wanted:
        found = SESSION_SOURCES[name]["find"](cwd)
        if found and (best is None or mtime(found[0]) > best[0]):
            best = (mtime(found[0]), found[0], name)

    if best is None:
        looked = ", ".join(
            f"{SESSION_SOURCES[n]['label']} ({project_dir_for(cwd) if n == 'claude' else codex_home() / 'sessions'})"
            for n in wanted
        )
        die(f"no session found for {cwd}.\nLooked in: {looked}\n"
            "Pass --transcript /path/to/session.jsonl to name one explicitly.")

    return best[1], best[2]


def is_freshair_child(path: Path) -> bool:
    """True if this transcript is a review we ourselves spawned.

    A CLI backend run in the project directory leaves its own session log next
    to the real one, and it is always the newest. Without this check the
    fallback would review the reviewer.
    """
    try:
        with path.open("r", encoding="utf-8", errors="replace") as fh:
            for _ in range(40):
                line = fh.readline()
                if not line:
                    break
                if is_own_payload(line):
                    return True
    except OSError:
        pass
    return False


# --------------------------------------------------------------------------
# parsing the transcript
# --------------------------------------------------------------------------

def clip(text: str, cap: int) -> str:
    text = text.rstrip()
    if len(text) <= cap:
        return text
    head = text[: cap // 2]
    tail = text[-cap // 2 :]
    return f"{head}\n… [{len(text) - cap} chars elided] …\n{tail}"


def block_text(block) -> str:
    """Flatten one content block into readable text."""
    if isinstance(block, str):
        return block
    if not isinstance(block, dict):
        return ""

    btype = block.get("type")

    if btype == "text":
        return block.get("text", "")

    if btype == "thinking":
        return ""  # handled by the caller, which knows whether to keep it

    if btype == "tool_use":
        name = block.get("name", "tool")
        args = block.get("input", {})
        if isinstance(args, dict):
            # Show the arguments that carry meaning, skip the bulk payloads.
            interesting = {}
            for key in ("command", "file_path", "pattern", "path", "url",
                        "prompt", "description", "query", "old_string"):
                if key in args:
                    interesting[key] = clip(str(args[key]), 400)
            rendered = json.dumps(interesting, ensure_ascii=False) if interesting else ""
        else:
            rendered = clip(str(args), 400)
        return f"[tool: {name}] {rendered}"

    if btype == "tool_result":
        content = block.get("content", "")
        if isinstance(content, list):
            content = "\n".join(block_text(c) for c in content)
        text = clip(str(content), TOOL_RESULT_CAP)
        marker = " (error)" if block.get("is_error") else ""
        return f"[tool result{marker}]\n{text}"

    if btype == "image":
        return "[image]"

    return ""


def parse_transcript(path: Path, keep_thinking: bool, source: str = "claude") -> list[dict]:
    """Return a list of {role, text, ts} turns, oldest first."""
    if source == "codex":
        return parse_codex(path, keep_thinking)
    turns: list[dict] = []

    with path.open("r", encoding="utf-8", errors="replace") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            try:
                rec = json.loads(line)
            except json.JSONDecodeError:
                continue

            if rec.get("type") not in ("user", "assistant"):
                continue
            if rec.get("isSidechain"):
                continue  # subagent chatter, not the main thread

            msg = rec.get("message") or {}
            role = msg.get("role") or rec.get("type")
            content = msg.get("content")

            # A "user" record that is nothing but tool results is the harness
            # feeding output back, not the human speaking. Label it honestly so
            # the outside reader can tell who actually said what.
            if role == "user" and isinstance(content, list) and content and all(
                isinstance(b, dict) and b.get("type") in ("tool_result", "image")
                for b in content
            ):
                role = "tool"

            parts: list[str] = []
            if isinstance(content, str):
                parts.append(content)
            elif isinstance(content, list):
                for block in content:
                    if isinstance(block, dict) and block.get("type") == "thinking":
                        if keep_thinking:
                            think = block.get("thinking", "")
                            if think.strip():
                                parts.append(f"[thinking] {think}")
                        continue
                    rendered = block_text(block)
                    if rendered.strip():
                        parts.append(rendered)

            text = "\n".join(p for p in parts if p.strip()).strip()
            if not text:
                continue

            # Claude Code's own injected reminders are noise to an outside reader.
            if role in ("user", "tool") and text.startswith("<system-reminder>") and text.endswith("</system-reminder>"):
                continue
            text = re.sub(r"<system-reminder>.*?</system-reminder>", "", text, flags=re.S).strip()
            if not text:
                continue

            # A previous freshair run whose payload was logged into this session.
            # Treating it as a human instruction would make each review the
            # input to the next one.
            if is_own_payload(text):
                continue

            turns.append({"role": role, "text": text, "ts": rec.get("timestamp", "")})

    return turns


# --------------------------------------------------------------------------
# shaping it to fit
# --------------------------------------------------------------------------

def render_turns(turns: list[dict]) -> str:
    out = []
    for i, t in enumerate(turns, 1):
        who = {"user": "HUMAN", "assistant": "AGENT"}.get(t["role"], "TOOL OUTPUT")
        out.append(f"--- turn {i} · {who} ---\n{t['text']}")
    return "\n\n".join(out)


def fit_to_budget(turns: list[dict], budget: int, head_turns: int) -> tuple[str, dict]:
    """
    Keep the opening turns (the original goal — the single most important thing
    for spotting drift) and as many recent turns as fit. Elide the middle.
    """
    stats = {"total_turns": len(turns), "kept_turns": len(turns), "elided_turns": 0}

    full = render_turns(turns)
    if len(full) <= budget:
        return full, stats

    head = turns[:head_turns]
    head_text = render_turns(head)
    if len(head_text) > budget:
        # Pathological case: the opening turns alone blow the budget. Keep the
        # original ask visible rather than dropping it.
        stats["kept_turns"] = len(head)
        stats["elided_turns"] = len(turns) - len(head)
        return clip(head_text, budget), stats

    tail: list[dict] = []
    used = len(head_text)
    for t in reversed(turns[head_turns:]):
        chunk = len(t["text"]) + 40
        if used + chunk > budget:
            break
        tail.append(t)
        used += chunk
    tail.reverse()

    elided = len(turns) - len(head) - len(tail)
    stats["kept_turns"] = len(head) + len(tail)
    stats["elided_turns"] = elided

    gap = (
        f"\n\n--- [{elided} turns from the middle of the session were elided to fit; "
        f"the opening and the most recent work are both intact] ---\n\n"
    )
    return head_text + gap + render_turns(tail), stats


GOAL_TURN_CAP = 6_000
CLAIM_CAP = 4_000


# Continuations the harness injects as user turns. They carry no requirement,
# and listing them as goals dilutes the real ones.
BOILERPLATE = {
    "continue from where you left off.",
    "continue",
    "continue.",
    "go on",
    "keep going",
    "please continue",
}


# Harness notices delivered as user turns — "[Request interrupted by user]" and
# friends. They report on the session, they do not ask for anything.
HARNESS_NOTICE = re.compile(r"^\[[^\]\n]{0,120}\]$")

# Invoking any slash command injects two synthetic user turns: a wrapper naming
# the command, and the skill's own SKILL.md body. Left alone, running FreshAir
# files its own documentation as one of the human's instructions.
COMMAND_WRAPPER = re.compile(
    r"^<command-message>.*?</command-message>\s*"
    r"<command-name>.*?</command-name>\s*"
    r"(?:<command-args>(?P<args>.*?)</command-args>)?\s*$",
    re.S,
)
SKILL_BODY = re.compile(r"^Base directory for this skill:\s*\S")


def unwrap_instruction(text: str) -> str:
    """The human's words, with harness scaffolding removed.

    Returns "" for a turn that carried no instruction of its own.
    """
    if SKILL_BODY.match(text):
        return ""
    m = COMMAND_WRAPPER.match(text)
    if m:
        return (m.group("args") or "").strip()
    return text


def goal_instructions(turns: list[dict], goal_turns: int) -> list[str]:
    """What the human actually asked for, and nothing the agent said back.

    The human's messages are the requirements. The agent's are where the
    rationalization lives, which is the whole thing we are trying not to ship.
    """
    texts = []
    for turn in turns:
        if turn["role"] != "user":
            continue
        text = unwrap_instruction(turn["text"].strip())
        if not text or text.lower() in BOILERPLATE or HARNESS_NOTICE.match(text):
            continue
        # An instruction cut off mid-send and retyped supersedes the fragment it
        # extends; listing both reads as two separate requirements.
        if texts and text.startswith(texts[-1]):
            texts[-1] = text
        else:
            texts.append(text)
    return texts[:goal_turns] if goal_turns > 0 else texts


def render_goal(kept: list[str], budget: int | None = None) -> str:
    """The instructions, dropping from the middle if they will not fit.

    The first instruction is the original ask and the last is the newest
    steering; losing either is what makes drift invisible, so the middle goes
    first — the same rule the full-transcript path uses.
    """
    if not kept:
        return "(no human instructions found in this session)"

    def render(items: list[str], gap: str = "") -> str:
        body = "\n\n".join(
            f"--- instruction {i} ---\n{clip(text, GOAL_TURN_CAP)}"
            for i, text in enumerate(items, 1)
        )
        return body + gap

    out = render(kept)
    if budget is None or len(out) <= budget or len(kept) <= 2:
        return out

    head, tail = [kept[0]], [kept[-1]]
    middle = kept[1:-1]
    while middle and len(render(head + middle + tail)) > budget:
        middle.pop(len(middle) // 2)   # drop from the centre outwards

    dropped = len(kept) - len(head) - len(middle) - len(tail)
    body = render(head + middle + tail)
    if dropped:
        body += (f"\n\n--- [{dropped} instruction(s) from the middle were "
                 f"elided to fit; the original ask and the newest steering are "
                 f"both intact] ---")
    return clip(body, budget)


def extract_goal(turns: list[dict], goal_turns: int, budget: int | None = None) -> str:
    return render_goal(goal_instructions(turns, goal_turns), budget)


def fit_fresh(goal: str, repo_block: str, diff_block: str, claim_block: str,
              budget: int) -> tuple[str, str, str]:
    """Bound the whole fresh payload, sacrificing in order of dispensability.

    The diff is the biggest and the most compressible; the agent's own account
    is the least trustworthy; the goal is what everything else is judged
    against, so it is cut last and only from the middle.
    """
    room = budget - len(repo_block)

    goal_room = max(room // 2, 2_000)
    if len(goal) > goal_room:
        goal = clip(goal, goal_room)
    room -= len(goal)

    if len(claim_block) > max(room // 4, 0):
        claim_block = clip(claim_block, room // 4) if room > 0 else ""
    room -= len(claim_block)

    if len(diff_block) > room:
        diff_block = clip(diff_block, max(room, 0))

    return goal, diff_block, claim_block


def extract_claim(turns: list[dict]) -> str:
    """The agent's most recent account of where things stand.

    Included as a claim to be checked against the diff, not as evidence. Tool
    invocations are stripped — what is wanted is the self-report, not the log.
    """
    for turn in reversed(turns):
        if turn["role"] != "assistant":
            continue
        prose = [ln for ln in turn["text"].splitlines()
                 if not ln.startswith("[tool")]
        text = "\n".join(prose).strip()
        if text:
            return clip(text, CLAIM_CAP)
    return ""


SECRET_PATTERNS = [
    (re.compile(r"sk-or-v1-[A-Za-z0-9]{16,}"), "sk-or-v1-***REDACTED***"),
    (re.compile(r"sk-ant-[A-Za-z0-9\-_]{16,}"), "sk-ant-***REDACTED***"),
    (re.compile(r"sk-proj-[A-Za-z0-9\-_]{16,}"), "sk-proj-***REDACTED***"),
    (re.compile(r"\bsk-[A-Za-z0-9]{32,}"), "sk-***REDACTED***"),
    (re.compile(r"gh[pousr]_[A-Za-z0-9]{20,}"), "gh*_***REDACTED***"),
    (re.compile(r"AKIA[0-9A-Z]{16}"), "AKIA***REDACTED***"),
    (re.compile(r"AIza[0-9A-Za-z\-_]{30,}"), "AIza***REDACTED***"),
    (re.compile(r"xox[baprs]-[A-Za-z0-9\-]{10,}"), "xox*-***REDACTED***"),
    (re.compile(r"ey[A-Za-z0-9_\-]{10,}\.[A-Za-z0-9_\-]{10,}\.[A-Za-z0-9_\-]{10,}"), "***JWT-REDACTED***"),
    (re.compile(r"-----BEGIN [A-Z ]*PRIVATE KEY-----.*?-----END [A-Z ]*PRIVATE KEY-----", re.S), "***PRIVATE-KEY-REDACTED***"),
]


def redact(text: str) -> tuple[str, int]:
    count = 0
    for pattern, replacement in SECRET_PATTERNS:
        text, n = pattern.subn(replacement, text)
        count += n
    return text, count


# --------------------------------------------------------------------------
# repo context
# --------------------------------------------------------------------------

def git(args: list[str], cwd: Path) -> str:
    try:
        r = subprocess.run(
            ["git"] + args, cwd=cwd, capture_output=True, text=True, timeout=20
        )
        return r.stdout if r.returncode == 0 else ""
    except (OSError, subprocess.SubprocessError):
        return ""


def branch_base(cwd: Path) -> tuple[str, str]:
    """The ref this branch forked from, and the commit where it forked.

    Used when the working tree is clean: the work still exists, it is just
    committed, and a reviewer with no diff at all has nothing to judge.
    """
    head = git(["rev-parse", "--abbrev-ref", "HEAD"], cwd).strip()
    candidates = []

    resolved = git(["symbolic-ref", "--short", "refs/remotes/origin/HEAD"], cwd).strip()
    if resolved:
        candidates.append(resolved)
    candidates += ["origin/main", "origin/master", "main", "master"]

    for name in candidates:
        if name == head or name.endswith("/" + head):
            continue  # a branch cannot be diffed against itself
        if not git(["rev-parse", "--verify", "--quiet", name], cwd).strip():
            continue
        base = git(["merge-base", "HEAD", name], cwd).strip()
        if base:
            return name, base
    return "", ""


def repo_context(cwd: Path) -> tuple[str, str]:
    """Returns (summary_block, diff_block)."""
    if git(["rev-parse", "--is-inside-work-tree"], cwd).strip() != "true":
        return "", ""

    branch = git(["rev-parse", "--abbrev-ref", "HEAD"], cwd).strip()
    status = git(["status", "--short"], cwd).strip()
    log = git(["log", "--oneline", "-8"], cwd).strip()

    summary = "===== REPO STATE =====\n"
    if branch:
        summary += f"branch: {branch}\n"
    if log:
        summary += f"\nrecent commits:\n{log}\n"
    if status:
        summary += f"\nworking tree:\n{status}\n"
    summary += "======================\n\n"

    diff = git(["diff", "HEAD"], cwd)
    title = "UNCOMMITTED DIFF (the work under review)"

    if not diff.strip():
        diff = git(["diff"], cwd)

    if not diff.strip():
        # Clean tree. The work is committed, not absent — right after a commit
        # is exactly when a second opinion is worth asking for.
        ref, base = branch_base(cwd)
        if base:
            diff = git(["diff", base, "HEAD"], cwd)
            title = f"EVERYTHING THIS BRANCH CHANGED vs {ref} (the work under review)"

    if not diff.strip():
        return summary, ""

    diff_block = (
        f"\n===== {title} =====\n"
        + clip(diff, DIFF_CAP)
        + "\n===== END DIFF =====\n"
    )
    return summary, diff_block


# --------------------------------------------------------------------------
# calling OpenRouter
# --------------------------------------------------------------------------

def ask_openrouter(model: str, system: str, user: str, api_key: str,
                   temperature: float, timeout: int) -> dict:
    payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": system},
            {"role": "user", "content": user},
        ],
        "temperature": temperature,
    }
    req = urllib.request.Request(
        OPENROUTER_URL,
        data=json.dumps(payload).encode("utf-8"),
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
            # OpenRouter shows these on the user's activity page. The referer
            # is the repository, which is still named what-do-you-think; the
            # title is the tool.
            "HTTP-Referer": "https://github.com/jiaazhaoo/what-do-you-think",
            "X-Title": "FreshAir",
        },
        method="POST",
    )

    started = time.time()
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            body = json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as e:
        detail = e.read().decode("utf-8", "replace")[:600]
        return {"model": model, "error": f"HTTP {e.code}: {detail}"}
    except Exception as e:  # noqa: BLE001 — surface anything the network does
        return {"model": model, "error": f"{type(e).__name__}: {e}"}

    choices = body.get("choices") or []
    if not choices:
        return {"model": model, "error": f"no choices in response: {json.dumps(body)[:600]}"}

    return {
        "model": model,
        "text": (choices[0].get("message") or {}).get("content", "").strip(),
        "usage": body.get("usage") or {},
        "seconds": round(time.time() - started, 1),
    }


# --------------------------------------------------------------------------
# calling a locally installed, already-signed-in vendor CLI
# --------------------------------------------------------------------------

def cli_command(spec: dict, model: str | None, repo: Path | None = None) -> list[str]:
    """Flags first, then the model, then whatever must stay last — a stdin
    sentinel or a variadic list that would otherwise swallow what follows."""
    cmd = list(spec["cmd"])
    if repo and spec.get("dir_flag"):
        cmd += [spec["dir_flag"], str(repo)]
    if model and spec.get("model_flag"):
        cmd += [spec["model_flag"], model]
    return cmd + list(spec.get("tail") or [])


# Variables that tell a nested agent CLI which session it belongs to. Leaving
# them set makes the child append its own prompt to *this* session's transcript,
# which is the file we are reviewing. Auth-bearing variables are deliberately
# left alone.
CHILD_ENV_STRIP = (
    "CLAUDE_CODE_SESSION_ID",
    "CLAUDE_SESSION_ID",
    "CLAUDE_CODE_CHILD_SESSION",
    "CLAUDE_PROJECT_DIR",
    "CLAUDE_CODE_ENTRYPOINT",
    "CLAUDE_AFTER_LAST_COMPACT",
    "CLAUDE_CODE_DIAGNOSTICS_FILE",
)


def child_env() -> dict:
    env = dict(os.environ)
    for key in CHILD_ENV_STRIP:
        env.pop(key, None)
    return env


def ask_cli(backend: str, spec: dict, model: str | None, system: str, user: str,
            timeout: int, repo: Path) -> dict:
    """Run the reviewer outside the repository.

    An agent CLI files its session log under a directory derived from its
    working directory. Started inside the repo, the reviewer's own prompt lands
    in the very transcript we read — so the next review takes the last review as
    input. Running it from a scratch directory puts that log somewhere harmless,
    and `dir_flag` hands the repo back as readable.
    """
    cmd = cli_command(spec, model, repo)
    name = f"{backend}" + (f" · {model}" if model else "")

    started = time.time()
    try:
        with tempfile.TemporaryDirectory(prefix="freshair-") as scratch:
            proc = subprocess.run(
                cmd,
                input=f"{system}\n\n{user}",
                capture_output=True,
                text=True,
                timeout=timeout,
                cwd=scratch,
                env=child_env(),
            )
    except FileNotFoundError:
        return {"model": name, "error": f"{spec['cmd'][0]} is not installed or not on PATH"}
    except subprocess.TimeoutExpired:
        return {"model": name, "error": f"timed out after {timeout}s"}
    except OSError as e:
        return {"model": name, "error": f"{type(e).__name__}: {e}"}

    out = (proc.stdout or "").strip()
    if proc.returncode != 0 and not out:
        err = (proc.stderr or "").strip()[:800] or f"exit code {proc.returncode}"
        return {
            "model": name,
            "error": f"{' '.join(cmd)}\n{err}\n\n"
                     f"If this backend's flags have changed upstream, override "
                     f"them in .freshair.json under backends.{backend}.cmd",
        }
    if not out:
        return {"model": name, "error": f"{' '.join(cmd)} produced no output"}

    return {"model": name, "text": out, "usage": {}, "seconds": round(time.time() - started, 1)}


PROBE_PROMPT = "Reply with exactly this token and nothing else: FRESHAIR-OK"
PROBE_TOKEN = "FRESHAIR-OK"


def check_backends(backends: dict[str, dict], selected: list[str],
                   config: dict, timeout: int, repo: Path) -> int:
    """Actually call each backend with a one-token prompt.

    The command lines here are built from each vendor's documented flags, and
    vendors change flags. This turns "should work" into something the user can
    confirm on their own machine in a few seconds.
    """
    failures = 0

    # The in-progress line only makes sense on a terminal; carriage returns do
    # not overwrite anything in a pipe or a log file.
    live = sys.stdout.isatty()

    def progress(line: str) -> None:
        if live:
            print(line, end="\r", flush=True)

    def emit(line: str) -> None:
        print(("\r" + " " * 60 + "\r" if live else "") + line)

    for name in selected:
        if name == "openrouter":
            key = openrouter_key(config)
            if not key:
                emit("  ✗ openrouter — no key; run --set-key sk-or-v1-...")
                failures += 1
                continue
            model = (config.get("models") or DEFAULT_MODELS)[0]
            progress(f"  … openrouter ({model})")
            r = ask_openrouter(model, "", PROBE_PROMPT, key, 0.0, timeout)
            label = f"openrouter ({model})"
        else:
            spec = backends[name]
            binary = spec["cmd"][0]
            if not shutil.which(binary):
                emit(f"  – {name:<11} not installed ({binary} not on PATH)")
                continue
            cmd = " ".join(cli_command(spec, None, repo))
            progress(f"  … {name}")
            r = ask_cli(name, spec, None, "", PROBE_PROMPT, timeout, repo)
            label = f"{name:<11} {cmd}"

        if r.get("error"):
            emit(f"  ✗ {label}\n      {r['error'].splitlines()[0]}")
            failures += 1
        elif PROBE_TOKEN not in (r.get("text") or ""):
            emit(f"  ✗ {label}\n      responded, but not with the probe token: "
                 f"{(r.get('text') or '')[:120]!r}")
            failures += 1
        else:
            emit(f"  ✓ {label}   ({r['seconds']}s)")

    return failures


def resolve_backends(config: dict) -> dict[str, dict]:
    """Built-in CLI backends, with per-repo overrides layered on top."""
    merged = {k: dict(v) for k, v in CLI_BACKENDS.items()}
    for name, override in (config.get("backends") or {}).items():
        merged.setdefault(name, {"label": name, "vendor": name})
        merged[name].update(override)
    return merged


def reachable_backends(backends: dict[str, dict], api_key: str = "") -> list[str]:
    """Every reviewer this machine can actually reach, outsiders first.

    Independent reviewers that never saw each other's answers are the point:
    where two of them converge is worth much more than either one alone.
    """
    order = [b for b in AUTO_ORDER if b in backends]
    order += [b for b in backends if b not in order]
    found = [n for n in order if shutil.which(backends[n]["cmd"][0])]
    if api_key or os.environ.get("OPENROUTER_API_KEY", "").strip():
        found.append("openrouter")
    return found


def detect_backend(backends: dict[str, dict], api_key: str = "") -> str:
    """Pick a backend the user is already signed in to, outsiders first."""
    order = [b for b in AUTO_ORDER if b in backends]
    order += [b for b in backends if b not in order]

    non_anthropic = [b for b in order if backends[b].get("vendor") != "anthropic"]
    for name in non_anthropic:
        if shutil.which(backends[name]["cmd"][0]):
            return name

    if api_key or os.environ.get("OPENROUTER_API_KEY", "").strip():
        return "openrouter"

    for name in order:
        if shutil.which(backends[name]["cmd"][0]):
            return name

    return "openrouter"


# --------------------------------------------------------------------------

def die(msg: str) -> None:
    print(f"freshair: {msg}", file=sys.stderr)
    sys.exit(1)


USER_CONFIG = Path.home() / ".config" / "freshair" / "config.json"


def config_files(cwd: Path) -> list[tuple[Path, dict]]:
    """User-global first, then per-repo — later files win on conflict."""
    found = []
    for path in (USER_CONFIG,
                 Path.home() / ".config" / "wdyt" / "config.json",   # pre-rename
                 cwd / ".freshair.json",
                 cwd / ".wdyt.json"):                                # pre-rename
        if not path.is_file():
            continue
        try:
            found.append((path, json.loads(path.read_text(encoding="utf-8"))))
        except json.JSONDecodeError:
            print(f"freshair: ignoring malformed config at {path}", file=sys.stderr)
    return found


def load_config(cwd: Path) -> dict:
    merged: dict = {}
    for path, data in config_files(cwd):
        if "api_key" in data and path not in (USER_CONFIG,
                                              Path.home() / ".config" / "wdyt" / "config.json"):
            # A repo config gets committed. A key belongs in the user-global
            # one, which does not.
            print(f"freshair: ignoring api_key in {path} — it would be committed. "
                  f"Use --set-key, which writes to {USER_CONFIG}.", file=sys.stderr)
            data = {k: v for k, v in data.items() if k != "api_key"}
        merged.update(data)
    return merged


def openrouter_key(config: dict) -> str:
    """Environment first, so a shell export still overrides a stored key."""
    return (os.environ.get("OPENROUTER_API_KEY", "").strip()
            or str(config.get("api_key", "")).strip())


def write_user_config(update: dict) -> Path:
    USER_CONFIG.parent.mkdir(parents=True, exist_ok=True)
    current = {}
    if USER_CONFIG.is_file():
        try:
            current = json.loads(USER_CONFIG.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            pass
    current.update({k: v for k, v in update.items() if v is not None})
    USER_CONFIG.write_text(json.dumps(current, indent=2) + "\n", encoding="utf-8")
    try:
        USER_CONFIG.chmod(0o600)   # it can hold a key
    except OSError:
        pass
    return USER_CONFIG


# --------------------------------------------------------------------------
# Signing in to OpenRouter without handling the key
#
# OAuth PKCE: we hold a random secret, send only its hash to OpenRouter, and
# the user approves in a browser. The key comes back over a loopback callback
# and goes straight to disk — it is never shown, pasted, or put in a shell
# history. https://openrouter.ai/docs/guides/overview/auth/oauth
# --------------------------------------------------------------------------

OPENROUTER_AUTH_URL = "https://openrouter.ai/auth"
OPENROUTER_KEYS_URL = "https://openrouter.ai/api/v1/auth/keys"

CALLBACK_PAGE = b"""<!doctype html><meta charset="utf-8">
<title>FreshAir</title>
<style>body{font:16px system-ui;margin:4rem auto;max-width:28rem;color:#222}
code{background:#f4f4f5;padding:.15em .4em;border-radius:4px}</style>
<h2>Connected.</h2>
<p>Your OpenRouter key was saved to this machine. You can close this tab and go
back to the terminal.</p>
<p>Ask for an outside opinion with <code>/freshair</code>.</p>
"""


def pkce_pair() -> tuple[str, str]:
    """A verifier we keep, and the S256 challenge we hand out (RFC 7636)."""
    verifier = base64.urlsafe_b64encode(secrets.token_bytes(48)).decode().rstrip("=")
    digest = hashlib.sha256(verifier.encode("ascii")).digest()
    challenge = base64.urlsafe_b64encode(digest).decode().rstrip("=")
    return verifier, challenge


def await_oauth_code(timeout: int) -> tuple[str, "object"]:
    """Bind a loopback callback and return (auth_url_callback, server)."""
    received: dict[str, str] = {}

    class Handler(http.server.BaseHTTPRequestHandler):
        def do_GET(self):  # noqa: N802 — http.server's interface
            query = urllib.parse.parse_qs(urllib.parse.urlparse(self.path).query)
            received["code"] = (query.get("code") or [""])[0]
            received["error"] = (query.get("error") or [""])[0]
            self.send_response(200)
            self.send_header("Content-Type", "text/html; charset=utf-8")
            self.end_headers()
            self.wfile.write(CALLBACK_PAGE)

        def log_message(self, *a):  # keep the terminal clean
            pass

    server = http.server.HTTPServer(("127.0.0.1", 0), Handler)
    server.timeout = timeout
    return f"http://localhost:{server.server_port}/callback", (server, received)


def exchange_code(code: str, verifier: str, timeout: int) -> str:
    payload = json.dumps({
        "code": code,
        "code_verifier": verifier,
        "code_challenge_method": "S256",
    }).encode()
    req = urllib.request.Request(
        OPENROUTER_KEYS_URL, data=payload,
        headers={"Content-Type": "application/json"}, method="POST")
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            body = json.loads(resp.read().decode())
    except urllib.error.HTTPError as e:
        detail = e.read().decode("utf-8", "replace")[:300]
        hint = ""
        if e.code == 403:
            hint = ("\n  A 403 here usually means the browser session was not "
                    "signed in to OpenRouter. Sign in there first, then retry.")
        die(f"OpenRouter refused the exchange (HTTP {e.code}): {detail}{hint}")
    except Exception as e:  # noqa: BLE001
        die(f"could not reach OpenRouter: {type(e).__name__}: {e}")

    key = str(body.get("key", "")).strip()
    if not key:
        die(f"no key in OpenRouter's response: {json.dumps(body)[:300]}")
    return key


PENDING_LOGIN = "login-pending.json"
PENDING_TTL = 900   # seconds; a half-finished login should not linger


def pending_path() -> Path:
    return USER_CONFIG.parent / PENDING_LOGIN


def save_pending(verifier: str) -> None:
    pending_path().parent.mkdir(parents=True, exist_ok=True)
    pending_path().write_text(
        json.dumps({"code_verifier": verifier, "at": time.time()}), encoding="utf-8")
    try:
        pending_path().chmod(0o600)
    except OSError:
        pass


def take_pending() -> str:
    path = pending_path()
    if not path.is_file():
        die("no login in progress. Start one with --login, approve in the "
            "browser, then pass the code back with --login --code ...")
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        path.unlink(missing_ok=True)
        die("the pending login was unreadable. Run --login again.")
    path.unlink(missing_ok=True)
    if time.time() - float(data.get("at", 0)) > PENDING_TTL:
        die("that login attempt expired. Run --login again.")
    return str(data.get("code_verifier", ""))


def login_manually(timeout: int) -> int:
    """For a session whose browser is not on the user's machine.

    Nothing can listen on the user's localhost from here, so the callback is
    never delivered. The code still reaches them: OpenRouter redirects their
    browser to a localhost URL that fails to load, and the address bar holds it.
    """
    verifier, challenge = pkce_pair()
    save_pending(verifier)

    url = OPENROUTER_AUTH_URL + "?" + urllib.parse.urlencode({
        "callback_url": "http://localhost:8765/callback",
        "code_challenge": challenge,
        "code_challenge_method": "S256",
    })
    print("This session runs on a different machine from your browser, so the\n"
          "callback cannot reach it. Two steps instead:\n")
    print(f"1. Open this and approve:\n\n   {url}\n")
    print("2. Your browser will then fail to load a localhost page. That is\n"
          "   expected. Copy the code= value out of its address bar and run:\n")
    print("       /freshair --login --code PASTE_IT_HERE\n")
    print(f"(The attempt expires in {PENDING_TTL // 60} minutes.)")
    return 0


def finish_login(code: str, timeout: int) -> int:
    verifier = take_pending()
    key = exchange_code(code.strip(), verifier, timeout)
    path = write_user_config({"api_key": key})
    print(f"Connected. Key saved to {path} (mode 600); it was never displayed.")
    print("Try it:  /freshair --check")
    return 0


def openrouter_login(timeout: int, manual: bool = False) -> int:
    # A cloud or web session runs somewhere the user's browser cannot reach.
    if manual or os.environ.get("CLAUDE_CODE_REMOTE") or os.environ.get("SSH_CONNECTION"):
        return login_manually(timeout)

    verifier, challenge = pkce_pair()
    callback, (server, received) = await_oauth_code(timeout)

    url = OPENROUTER_AUTH_URL + "?" + urllib.parse.urlencode({
        "callback_url": callback,
        "code_challenge": challenge,
        "code_challenge_method": "S256",
    })

    opened = False
    try:
        opened = webbrowser.open(url)
    except Exception:  # noqa: BLE001 — a headless box has no browser
        opened = False

    print("Approve FreshAir in your browser." if opened else
          "Open this in a browser on THIS machine:")
    print(f"\n  {url}\n")
    if not opened:
        print("(No browser here. If this machine is not the one you are sitting\n"
              " at, stop and use:  --login --manual)\n")
    print(f"Waiting up to {timeout}s for the callback...", flush=True)

    server.handle_request()   # blocks until the browser calls back, or times out
    server.server_close()

    if received.get("error"):
        die(f"OpenRouter returned an error: {received['error']}")
    code = received.get("code", "")
    if not code:
        die("no authorization code came back — the browser never reached the "
            "callback, or it timed out. Nothing was saved.\n"
            "If your browser is on a different machine from this session, use:\n"
            "    --login --manual")

    key = exchange_code(code, verifier, timeout)
    path = write_user_config({"api_key": key})
    print(f"\nConnected. Key saved to {path} (mode 600); it was never displayed.")
    print("Try it:  freshair --check")
    return 0


def apply_profile(config: dict, name: str) -> dict:
    profiles = config.get("profiles") or {}
    if name not in profiles:
        known = ", ".join(profiles) or "(none defined)"
        die(f"no profile named {name!r}. Defined in {USER_CONFIG}: {known}")
    return profiles[name] or {}


def describe_config(cwd: Path, backends: dict) -> None:
    print("Config files, in order of precedence (later wins):")
    files = config_files(cwd)
    if not files:
        print(f"  (none) — --set-key or --save-default will create {USER_CONFIG}")
    for path, data in files:
        keys = ", ".join(k for k in data if k != "api_key")
        secret = " api_key=set" if data.get("api_key") else ""
        print(f"  {path}\n      {keys or '(empty)'}{secret}")

    config = load_config(cwd)
    print("\nResolved:")
    print(f"  backend  {config.get('backend', 'auto')}")
    print(f"  models   {', '.join(config.get('models') or DEFAULT_MODELS)}")
    print(f"  mode     {config.get('mode', 'fresh')}")

    key = openrouter_key(config)
    where = ("OPENROUTER_API_KEY" if os.environ.get("OPENROUTER_API_KEY", "").strip()
             else str(USER_CONFIG) if key else "not set")
    print(f"  api_key  {(key[:12] + '...') if key else '(none)'}  [{where}]")

    profiles = config.get("profiles") or {}
    print("\nProfiles:" if profiles else "\nProfiles: (none) — see --save-default")
    for name, body in profiles.items():
        bits = []
        if body.get("backend"):
            bits.append(f"backend={body['backend']}")
        if body.get("models"):
            bits.append("models=" + ",".join(body["models"]))
        print(f"  -p {name:<12} {'  '.join(bits)}")

    print("\nReachable right now: "
          + (", ".join(reachable_backends(backends, openrouter_key(config)))
             or "(nothing — see --check)"))


def main() -> None:
    cwd = Path(os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd()).resolve()
    config = load_config(cwd)
    backends = resolve_backends(config)

    ap = argparse.ArgumentParser(
        prog="freshair",
        description="FreshAir — get an outside opinion from a model that has "
                    "not seen this conversation.",
    )
    ap.add_argument("focus", nargs="*",
                    help="what to look at, e.g. 'is the caching layer worth it'")
    ap.add_argument("--mode", choices=["fresh", "full"],
                    default=config.get("mode", "fresh"),
                    help="fresh (default): send only the goal and the current "
                         "state, so the reviewer cannot be anchored by the "
                         "reasoning that got you here. full: send the whole "
                         "transcript, for 'where exactly did we go wrong'.")
    ap.add_argument("--goal-turns", type=int, default=int(config.get("goal_turns", 0)),
                    help="in fresh mode, use only the first N human "
                         "instructions as the goal (0 = all of them)")
    ap.add_argument("-b", "--backend", action="append", default=[],
                    help="auto (default) | all | " + " | ".join(list(backends) + ["openrouter"])
                         + ". Repeat or comma-separate to ask several "
                           "independent reviewers at once; 'all' asks every one "
                           "this machine can reach. CLI backends use the login "
                           "you already have; openrouter needs OPENROUTER_API_KEY.")
    ap.add_argument("-m", "--model", action="append", default=[],
                    help="model id; repeat or comma-separate to run several in "
                         "parallel. Omit on a CLI backend to use its own "
                         "default. With more than one backend selected, model "
                         "ids are not portable between vendors, so these apply "
                         "to openrouter only and each CLI uses its own default.")
    ap.add_argument("--transcript", help="path to a session .jsonl (default: this session)")
    ap.add_argument("--session-id", help="session id to look up, if autodetection picks wrong")
    ap.add_argument("--from", dest="source", choices=["auto", "claude", "codex"],
                    default=config.get("from", "auto"),
                    help="which agent's session to review. auto (default) takes "
                         "the most recently written session for this directory, "
                         "whichever host wrote it.")
    ap.add_argument("--budget", type=int,
                    default=int(config.get("budget", DEFAULT_BUDGET)),
                    help=f"max transcript characters to send (default {DEFAULT_BUDGET})")
    ap.add_argument("--head-turns", type=int, default=int(config.get("head_turns", 6)),
                    help="opening turns always kept, so drift stays visible (default 6)")
    ap.add_argument("--thinking", action="store_true",
                    help="include the agent's thinking blocks")
    ap.add_argument("--no-diff", action="store_true", help="do not attach the git diff")
    ap.add_argument("--no-claim", action="store_true",
                    help="in fresh mode, withhold the agent's own account of "
                         "where things stand, leaving only the goal and the diff")
    ap.add_argument("--no-redact", action="store_true",
                    help="skip the credential scrub (not recommended)")
    ap.add_argument("--lang", default=config.get("lang", "English"),
                    help="language for the review (default English; set \"lang\" "
                         "in .freshair.json to change it permanently)")
    ap.add_argument("--temperature", type=float, default=float(config.get("temperature", 0.7)))
    ap.add_argument("--timeout", type=int, default=int(config.get("timeout", 600)))
    ap.add_argument("-p", "--profile",
                    help="use a saved profile (see --show-config for the list)")
    ap.add_argument("--save-default", nargs="?", const="", metavar="NAME",
                    help="remember this call's --backend/--model choice. Bare, "
                         "it becomes the default; with a NAME it becomes a "
                         "profile you select with -p NAME.")
    ap.add_argument("--manual", action="store_true",
                    help="with --login: print the URL and take the code back by "
                         "hand, for when your browser is on another machine")
    ap.add_argument("--code", metavar="CODE",
                    help="with --login: finish a --manual login using the code "
                         "from your browser's address bar")
    ap.add_argument("--login", action="store_true",
                    help="connect OpenRouter in the browser — you approve, the "
                         "key is stored here, you never see or paste it")
    ap.add_argument("--set-key", metavar="KEY",
                    help="store an OpenRouter key in the user config (mode 600) "
                         "so no environment variable is needed")
    ap.add_argument("--show-config", action="store_true",
                    help="print where every setting comes from, and what is "
                         "reachable right now")
    ap.add_argument("--check", action="store_true",
                    help="probe each backend with a one-token prompt and report "
                         "which ones actually work on this machine")
    ap.add_argument("--dry-run", action="store_true",
                    help="print exactly what would be sent and how, call nothing")
    ap.add_argument("--save", metavar="PATH", help="also write the review to this file")
    args = ap.parse_args()

    if args.login or args.code:
        if args.code:
            sys.exit(finish_login(args.code, args.timeout))
        sys.exit(openrouter_login(args.timeout, manual=args.manual))

    if args.set_key:
        path = write_user_config({"api_key": args.set_key.strip()})
        print(f"Stored OpenRouter key in {path} (mode 600).")
        print("Nothing else to do — it is picked up automatically. "
              "An OPENROUTER_API_KEY in the environment still wins if set.")
        return

    if args.save_default is not None:
        chosen_backends = [b.strip() for e in args.backend for b in e.split(",") if b.strip()]
        chosen_models = [m.strip() for e in args.model for m in e.split(",") if m.strip()]
        if not chosen_backends and not chosen_models:
            die("--save-default needs something to save: pass -b and/or -m "
                "alongside it, e.g. -b openrouter -m openai/gpt-5.1 --save-default")
        entry = {}
        if chosen_backends:
            entry["backend"] = ",".join(chosen_backends)
        if chosen_models:
            entry["models"] = chosen_models

        if args.save_default:                      # a named profile
            existing = load_config(cwd).get("profiles") or {}
            existing[args.save_default] = entry
            path = write_user_config({"profiles": existing})
            print(f"Saved profile {args.save_default!r} in {path}.")
            print(f"Use it with:  /freshair -p {args.save_default}")
        else:                                      # the default for every call
            path = write_user_config(entry)
            print(f"Saved as the default in {path}: "
                  + "  ".join(f"{k}={v}" for k, v in entry.items()))
            print("Use it with:  /freshair")
        return

    if args.show_config:
        describe_config(cwd, backends)
        return

    if args.check:
        asked = [b.strip() for entry in args.backend for b in entry.split(",") if b.strip()]
        selected = ([b for b in asked if b not in ("auto", "all")]
                    or list(backends) + ["openrouter"])
        print("Probing backends (a real call each, one token of output):")
        sys.exit(1 if check_backends(backends, selected, config, args.timeout, cwd) else 0)

    profile = apply_profile(config, args.profile) if args.profile else {}
    api_key = openrouter_key(config)

    requested: list[str] = []
    for entry in (args.backend
                  or ([profile["backend"]] if profile.get("backend") else None)
                  or [config.get("backend", "auto")]):
        requested.extend(b.strip() for b in entry.split(",") if b.strip())

    selected: list[str] = []
    for name in requested:
        if name == "auto":
            selected.append(detect_backend(backends, api_key))
        elif name == "all":
            # Every independent reviewer this machine can actually reach.
            selected.extend(reachable_backends(backends, api_key))
        elif name == "openrouter" or name in backends:
            selected.append(name)
        else:
            die(f"unknown backend {name!r}. Known: "
                + ", ".join(list(backends) + ["openrouter", "auto", "all"]))

    selected = list(dict.fromkeys(selected))  # keep order, drop repeats
    if not selected:
        die("no backend available. Install and sign in to codex or gemini, "
            "or set OPENROUTER_API_KEY.")

    any_cli = any(b != "openrouter" for b in selected)

    asked_models: list[str] = []
    for entry in (args.model or profile.get("models") or []):
        asked_models.extend(m.strip() for m in entry.split(",") if m.strip())

    def models_for(name: str) -> list[str | None]:
        if name == "openrouter":
            return list(asked_models or profile.get("models")
                        or config.get("models") or DEFAULT_MODELS)
        # Model ids are not portable between vendors, so an explicit -m only
        # reaches a CLI backend when it is the only one running.
        if asked_models and len(selected) == 1:
            return list(asked_models)
        return list(backends[name].get("models") or []) or [None]

    jobs: list[tuple[str, str | None]] = [
        (name, model) for name in selected for model in models_for(name)
    ]

    # ---- build the payload ------------------------------------------------
    path, source = find_transcript(args.transcript, cwd, args.session_id, args.source)
    turns = parse_transcript(path, keep_thinking=args.thinking, source=source)
    if not turns:
        die(f"no readable turns in {path}")

    repo_block, diff_block = ("", "")
    if not args.no_diff:
        repo_block, diff_block = repo_context(cwd)

    focus_block = ""
    focus = " ".join(args.focus).strip()
    if focus:
        focus_block = f"The human specifically wants your read on: {focus}\n\n"

    def system_for(name: str) -> str:
        rule = VERIFY_RULE_API if name == "openrouter" else VERIFY_RULE_CLI
        template = SYSTEM_PROMPT_FRESH if args.mode == "fresh" else SYSTEM_PROMPT_FULL
        return template.format(verify_rule=rule)

    verify_rule = VERIFY_RULE_CLI if any_cli else VERIFY_RULE_API

    if args.mode == "fresh":
        goal = extract_goal(turns, args.goal_turns, args.budget)
        claim = "" if args.no_claim else extract_claim(turns)
        claim_block = ""
        if claim:
            claim_block = (
                "\n===== THE AGENT'S OWN ACCOUNT OF WHERE THIS STANDS =====\n"
                "(A claim, not evidence. Check it against the diff above.)\n\n"
                f"{claim}\n"
                "===== END ACCOUNT =====\n"
            )
        if not diff_block and not repo_block:
            claim_block += (
                "\n(No git repository here, so there is no diff to check the "
                "account against.)\n"
            )

        goal, diff_block, claim_block = fit_fresh(
            goal, repo_block, diff_block, claim_block, args.budget)

        system_msg = SYSTEM_PROMPT_FRESH.format(verify_rule=verify_rule)
        user_msg = USER_TEMPLATE_FRESH.format(
            focus_block=focus_block,
            goal=goal,
            repo_block=repo_block,
            diff_block=diff_block,
            claim_block=claim_block,
            lang=args.lang,
        )
        shown = len(goal_instructions(turns, args.goal_turns))
        stats = {"total_turns": len(turns), "kept_turns": shown,
                 "elided_turns": len(turns) - shown}
        shape = (f"goal: {shown} human instruction(s) + current state; "
                 f"{len(turns) - shown} turns of agent reasoning withheld")
    else:
        transcript, stats = fit_to_budget(turns, args.budget, args.head_turns)
        system_msg = SYSTEM_PROMPT_FULL.format(verify_rule=verify_rule)
        user_msg = USER_TEMPLATE_FULL.format(
            focus_block=focus_block,
            repo_block=repo_block,
            transcript=transcript,
            diff_block=diff_block,
            lang=args.lang,
        )
        shape = (f"turns: {stats['kept_turns']}/{stats['total_turns']} kept"
                 + (f", {stats['elided_turns']} elided from the middle"
                    if stats["elided_turns"] else ""))

    redacted_count = 0
    if not args.no_redact:
        user_msg, redacted_count = redact(user_msg)

    def route_for(name: str) -> str:
        if name == "openrouter":
            return "OpenRouter API"
        return (f"{backends[name].get('label', name)} — local CLI, your own "
                f"login, nothing routed through a third party")

    route = " + ".join(route_for(n) for n in selected)

    vendors = {("openrouter" if n == "openrouter" else backends[n].get("vendor"))
               for n in selected}
    warning = ""
    if not [v for v in vendors if v != HOST_VENDOR]:
        # Escaping the context is the main mechanism and it is doing the work
        # here; a different vendor is an increment on top, not the pass mark.
        # Overstating that drives people to skip the tool over setup friction.
        warning = (
            f"\nNote: same vendor as the agent you are talking to "
            f"({', '.join(selected)}). The fresh context is the main mechanism "
            "and it is working — that alone finds most of what this tool finds. "
            "A different vendor additionally covers mistakes both models would "
            "make; install codex or gemini if you want that too.\n"
        )
    elif len(vendors) == 1:
        warning = (
            "\n(One reviewer. Two that never saw each other's answer disagree "
            "in the places worth looking — try --backend all.)\n"
        )

    header = (
        f"transcript: {path}  ({SESSION_SOURCES[source]['label']})\n"
        f"mode: {args.mode}\n"
        f"{shape}\n"
        f"payload: {len(user_msg):,} chars (~{len(user_msg)//4:,} tokens)\n"
        f"backend: {route}\n"
        + "reviewers: "
        + ", ".join(f"{b}" + (f" · {m}" if m else "") for b, m in jobs) + "\n"
        + (f"redacted: {redacted_count} credential-shaped strings\n" if redacted_count else "")
        + warning
    )

    if args.dry_run:
        print(header)
        for name, m in jobs:
            if name == "openrouter":
                print(f"would POST to OpenRouter as {m}")
            else:
                print("would run: " + " ".join(cli_command(backends[name], m, cwd))
                      + "\n           (prompt on stdin, from a scratch cwd)")
        print()
        print("=" * 70)
        print("SYSTEM:\n" + system_msg)
        print("=" * 70)
        print("USER:\n" + user_msg)
        return

    # ---- dispatch ---------------------------------------------------------
    for name in selected:
        if name == "openrouter":
            if not api_key:
                die("No OpenRouter key. Either store one with\n"
                    "    freshair --set-key sk-or-v1-...\n"
                    "(get it at https://openrouter.ai/keys), or use a CLI you "
                    "are already signed in to: --backend codex | gemini | claude")
        elif not shutil.which(backends[name]["cmd"][0]):
            die(f"backend {name!r} needs {backends[name]['cmd'][0]!r} on PATH, "
                f"and it is not there.\nInstall and sign in to it, pick another "
                f"with --backend, or use --backend openrouter.")

    def run(job: tuple[str, str | None]) -> dict:
        name, model = job
        if name == "openrouter":
            r = ask_openrouter(model, system_for(name), user_msg, api_key,
                               args.temperature, args.timeout)
        else:
            r = ask_cli(name, backends[name], model, system_for(name),
                        user_msg, args.timeout, cwd)
        r["backend"] = name
        return r

    print(header, file=sys.stderr)

    with concurrent.futures.ThreadPoolExecutor(max_workers=max(1, len(jobs))) as pool:
        results = list(pool.map(run, jobs))

    # ---- report -----------------------------------------------------------
    def reviewer(r: dict) -> str:
        name = r.get("backend", "")
        model = r.get("model", "")
        return model if model.startswith(name) else f"{name} · {model}" if name else model

    provenance = warning.strip()
    chunks = [f"<!-- {OUTPUT_MARKER} -->\n" + f"# Outside opinion\n\n_{datetime.now(timezone.utc).astimezone():%Y-%m-%d %H:%M} · via {route}_\n"
              + (f"\n> {provenance}\n" if provenance else "")]
    failures = 0
    for r in results:
        if r.get("error"):
            failures += 1
            chunks.append(f"\n---\n\n## ❌ {reviewer(r)}\n\n```\n{r['error']}\n```\n")
            continue
        usage = r.get("usage") or {}
        meta = f"{r['seconds']}s"
        if usage.get("total_tokens"):
            meta += f" · {usage['total_tokens']:,} tokens"
        chunks.append(f"\n---\n\n## 🔎 {reviewer(r)}\n\n_{meta}_\n\n{r['text']}\n")

    if len([r for r in results if not r.get("error")]) > 1:
        chunks.append(
            "\n---\n\n## Reading several reviewers\n\n"
            "These reviewers never saw each other's answers. Where two of them "
            "independently land on the same problem, that is the strongest "
            "signal available here. Where only one raises something, it is a "
            "lead, not a finding. Where they contradict each other, the "
            "disagreement itself is usually the interesting part.\n"
        )

    out = "".join(chunks)
    print(out)

    if args.save:
        Path(args.save).expanduser().write_text(out, encoding="utf-8")
        print(f"\nsaved to {args.save}", file=sys.stderr)

    if failures == len(results):
        sys.exit(1)


if __name__ == "__main__":
    main()
