#!/usr/bin/env python3
"""
FreshAir — put the current work in front of a model that has never seen this
conversation, and bring back what it says.

By default only two things leave: every instruction the human gave, and the
current state of the code. The hundred turns of agent reasoning in between are
withheld on purpose — a reviewer that reads those justifications first is
anchored by them, agrees, and tells you nothing you did not already believe.

Nothing here is summarized by the agent that is already stuck. This script reads
the session log itself.

Stdlib only. No install step.
"""

# `X | None` in a signature is evaluated at def time before 3.10; this defers
# every annotation so the script runs on whatever python the user already has.
from __future__ import annotations

import argparse
import concurrent.futures
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import time
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

OPENROUTER_URL = "https://openrouter.ai/api/v1/chat/completions"

DEFAULT_MODELS = ["openai/gpt-5.1", "google/gemini-3-pro"]

# Locally installed vendor CLIs, each already signed in as the user. No API key
# changes hands and no transcript passes through a third party — the request
# goes straight from this machine to the vendor the user already pays.
#
# Every field here is overridable from .freshair.json under "backends", so a changed
# upstream flag is a config edit rather than a patch.
CLI_BACKENDS: dict[str, dict] = {
    "codex": {
        # `codex exec` already defaults to a read-only sandbox; say so explicitly
        # so a future default change cannot hand a reviewer write access.
        "cmd": ["codex", "exec", "--sandbox", "read-only",
                "--ask-for-approval", "never"],
        "tail": ["-"],               # `-` makes codex read the prompt from stdin
        "model_flag": "-m",
        "label": "Codex CLI (your ChatGPT login)",
        "vendor": "openai",
    },
    "gemini": {
        "cmd": ["gemini"],           # headless gemini reads a piped prompt
        "tail": [],
        "model_flag": "-m",
        "label": "Gemini CLI (your Google login)",
        "vendor": "google",
    },
    "claude": {
        "cmd": ["claude", "-p"],
        # Variadic, so it goes last — anything after it gets swallowed.
        "tail": ["--disallowed-tools", "Edit", "Write", "NotebookEdit", "Bash"],
        "model_flag": "--model",
        # Hands the repo back as a readable directory after we move the child
        # out of it. Backends without a known equivalent simply review the
        # payload, which is what the API backends do anyway.
        "dir_flag": "--add-dir",
        "label": "Claude Code CLI (your Anthropic login)",
        "vendor": "anthropic",
    },
}

# The vendor whose agent is running this skill. Asking it for a second opinion
# is the weakest version of this tool — same weights, same blind spots — so it
# is ranked last and called out at runtime when it is what we fall back to.
HOST_VENDOR = "anthropic" if os.environ.get("CLAUDECODE") else None

AUTO_ORDER = ["codex", "gemini", "claude"]

# Rough budget for the transcript we ship out, in characters.
DEFAULT_BUDGET = 140_000
TOOL_RESULT_CAP = 1_200
DIFF_CAP = 40_000

# A CLI backend writes its own session log. If it ever lands in the transcript
# we later read, the payload must be recognisable as ours rather than as
# something a human typed — otherwise each review feeds itself into the next.
FRESHAIR_MARKER = "freshair-review-request"
MARKER_LINE = (
    f"<!-- {FRESHAIR_MARKER}: generated by FreshAir, not typed by a human -->\n"
)

# Payloads written before this marker existed, and before the tool was renamed.
# Transcripts polluted by an older version are still out there being read, so
# these have to keep matching for as long as those sessions do.
LEGACY_SIGNATURES = (
    "wdyt-review-request",
    "You are an outside reviewer. You were NOT part of the conversation",
    "You are being handed a piece of work cold.",
)

SYSTEM_PROMPT_FULL = MARKER_LINE + """\
You are an outside reviewer. You were NOT part of the conversation you are about \
to read, and that is the entire reason you were called in.

The transcript below is a working session between a human and a coding agent. \
The agent has been in this conversation for a long time. It is now anchored: it \
keeps building on its own earlier decisions, treats its own assumptions as \
settled fact, and has stopped generating genuinely new options. The human called \
you because they suspect this has happened but cannot see it from inside.

You are reading the raw transcript, not a summary. Nobody has filtered it for \
you. That means the mistakes are still visible in it — an assumption that got \
made once and never questioned again, a requirement from the first message that \
quietly got dropped, a hard problem that got redefined into an easier one.

Rules:
- Judge the work, not the effort. Do not open with praise. Do not soften.
- Be specific. Point at the actual turn, decision, or line of code. "Consider \
edge cases" is worthless; "the retry loop added around turn 12 never resets \
`attempt`, so the backoff is wrong after the first failure" is worth reading.
- The agent's framing is not evidence. If the transcript takes something for \
granted, that is exactly the thing to poke.
- If they are actually on the right track, say so plainly and briefly, and spend \
your words on the sharpest remaining risk instead of manufacturing complaints.
{verify_rule}
"""

VERIFY_RULE_API = (
    "- You cannot run anything. If a claim in the transcript needs "
    "verification, say what you would run to check it."
)

VERIFY_RULE_CLI = (
    "- You are running in the repository this session is about. If a claim in "
    "the transcript needs checking, open the file and check it rather than "
    "taking the transcript's word for it. Do not modify anything."
)

SYSTEM_PROMPT_FRESH = MARKER_LINE + """\
You are being handed a piece of work cold.

You are deliberately NOT being shown how it got here. Somewhere behind this, a \
human and a coding agent went back and forth for a long time, and the agent \
ended up anchored on its own earlier decisions — treating its assumptions as \
settled and no longer generating new options. Showing you that reasoning would \
anchor you exactly the same way. So it was withheld.

You get two things and nothing else: what the human asked for, and what exists \
right now. Judge the second against the first, from scratch.

Rules:
- Reason forward from the goal, not backward from the code. The obvious \
approach to the stated problem may not be the approach that was taken — you \
are the only one left in this loop who can still see that.
- Do not assume a decision was considered and rejected for a good reason. If \
something looks wrong, the likeliest explanation is that nobody ever asked.
- Judge the work, not the effort. Do not open with praise. Do not soften.
- Be specific: name the file, the function, the line. "Consider edge cases" is \
worthless; "`fit_to_budget` drops the opening turns when the head alone \
exceeds the budget, so the original goal disappears exactly when it matters \
most" is worth reading.
- If the work does meet the goal, say so plainly and briefly, then spend your \
words on the sharpest remaining risk rather than manufacturing complaints.
{verify_rule}
"""

USER_TEMPLATE_FRESH = """\
{focus_block}\
===== THE GOAL — every instruction the human gave, verbatim =====
{goal}
===== END GOAL =====

{repo_block}{diff_block}{claim_block}
Answer in this structure, in {lang}:

## 判断 / Verdict
One line, one of: KEEP GOING / ADJUST COURSE / STOP AND RETHINK — plus one \
sentence of why.

## 这东西在解决那个问题吗 / Does this solve the stated problem
Hold what exists against the goal. What the goal asked for that is missing, and \
what is here that the goal never asked for.

## 你会怎么做 / How you would have approached it
Knowing only the goal, what would you reach for? If it differs from what is \
here, say concretely what the difference buys — and if it does not differ, say \
that, because it is real information.

## 没人质疑过的假设 / Unexamined assumptions
What does this design take for granted? For each: why it might be wrong, and \
what it costs if it is.

## 具体问题 / Concrete problems
Bugs, gaps, broken logic, missing cases. Cite file and line. Ordered by how \
much damage they do.

## 能删掉什么 / What can be deleted
Anything here not earning its place? Say so even if it is most of the work.
"""

USER_TEMPLATE_FULL = """\
Read the session transcript below, then answer in the structure given at the end.

{focus_block}
{repo_block}
===== BEGIN SESSION TRANSCRIPT =====
{transcript}
===== END SESSION TRANSCRIPT =====
{diff_block}
Answer in this structure, in {lang}:

## 判断 / Verdict
One line, one of: KEEP GOING / ADJUST COURSE / STOP AND RETHINK — plus one \
sentence of why.

## 跑偏了吗 / Drift
What did the human ask for in their earliest messages, and is that still what is \
being built? Quote the original ask. If it drifted, name the turn where it \
drifted.

## 没人质疑过的假设 / Unexamined assumptions
Things the transcript treats as settled that are not. For each: why it might be \
wrong, and what it would cost if it is.

## 具体问题 / Concrete problems
Bugs, gaps, broken logic, missing cases. Cite where. Ordered by how much damage \
they do.

## 更简单的做法 / The simpler path
Is there a materially simpler approach that was never considered? Is there a \
chunk of this that could just be deleted? Say so even if it means throwing away \
most of the work.

## 如果我从零开始 / If I started fresh
Two or three sentences: knowing only the original goal, how would you have \
approached this? If it is the same as what they did, say that — it is useful \
information.
"""


# --------------------------------------------------------------------------
# locating the transcript
# --------------------------------------------------------------------------

def project_dir_for(cwd: Path) -> Path:
    """Claude Code slugifies the cwd: every non-alphanumeric char becomes '-'."""
    slug = re.sub(r"[^a-zA-Z0-9]", "-", str(cwd))
    return Path.home() / ".claude" / "projects" / slug


def find_transcript(explicit: str | None, cwd: Path, session_id: str | None = None) -> Path:
    if explicit:
        p = Path(explicit).expanduser()
        if not p.is_file():
            die(f"transcript not found: {p}")
        return p

    pdir = project_dir_for(cwd)
    if not pdir.is_dir():
        die(
            f"no session directory for {cwd} (looked in {pdir}).\n"
            "Pass --transcript /path/to/session.jsonl explicitly."
        )

    session_id = (
        session_id
        or os.environ.get("CLAUDE_SESSION_ID")
        or os.environ.get("CLAUDE_CODE_SESSION_ID")
    )
    if session_id:
        candidate = pdir / f"{session_id}.jsonl"
        if candidate.is_file():
            return candidate

    # Fall back to the most recently written transcript in this project — in a
    # live session that is the one being appended to right now.
    files = sorted(pdir.glob("*.jsonl"), key=lambda f: f.stat().st_mtime, reverse=True)
    if not files:
        die(f"no .jsonl transcripts in {pdir}")
    for candidate in files:
        if not is_freshair_child(candidate):
            return candidate
    return files[0]


def is_freshair_child(path: Path) -> bool:
    """True if this transcript is a review we ourselves spawned.

    A CLI backend run in the project directory leaves its own session log next
    to the real one, and it is always the newest. Without this check the
    fallback would review the reviewer.
    """
    try:
        with path.open("r", encoding="utf-8", errors="replace") as fh:
            for _ in range(40):
                line = fh.readline()
                if not line:
                    break
                if FRESHAIR_MARKER in line or any(sig in line for sig in LEGACY_SIGNATURES):
                    return True
    except OSError:
        pass
    return False


# --------------------------------------------------------------------------
# parsing the transcript
# --------------------------------------------------------------------------

def clip(text: str, cap: int) -> str:
    text = text.rstrip()
    if len(text) <= cap:
        return text
    head = text[: cap // 2]
    tail = text[-cap // 2 :]
    return f"{head}\n… [{len(text) - cap} chars elided] …\n{tail}"


def block_text(block) -> str:
    """Flatten one content block into readable text."""
    if isinstance(block, str):
        return block
    if not isinstance(block, dict):
        return ""

    btype = block.get("type")

    if btype == "text":
        return block.get("text", "")

    if btype == "thinking":
        return ""  # handled by the caller, which knows whether to keep it

    if btype == "tool_use":
        name = block.get("name", "tool")
        args = block.get("input", {})
        if isinstance(args, dict):
            # Show the arguments that carry meaning, skip the bulk payloads.
            interesting = {}
            for key in ("command", "file_path", "pattern", "path", "url",
                        "prompt", "description", "query", "old_string"):
                if key in args:
                    interesting[key] = clip(str(args[key]), 400)
            rendered = json.dumps(interesting, ensure_ascii=False) if interesting else ""
        else:
            rendered = clip(str(args), 400)
        return f"[tool: {name}] {rendered}"

    if btype == "tool_result":
        content = block.get("content", "")
        if isinstance(content, list):
            content = "\n".join(block_text(c) for c in content)
        text = clip(str(content), TOOL_RESULT_CAP)
        marker = " (error)" if block.get("is_error") else ""
        return f"[tool result{marker}]\n{text}"

    if btype == "image":
        return "[image]"

    return ""


def parse_transcript(path: Path, keep_thinking: bool) -> list[dict]:
    """Return a list of {role, text, ts} turns, oldest first."""
    turns: list[dict] = []

    with path.open("r", encoding="utf-8", errors="replace") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            try:
                rec = json.loads(line)
            except json.JSONDecodeError:
                continue

            if rec.get("type") not in ("user", "assistant"):
                continue
            if rec.get("isSidechain"):
                continue  # subagent chatter, not the main thread

            msg = rec.get("message") or {}
            role = msg.get("role") or rec.get("type")
            content = msg.get("content")

            # A "user" record that is nothing but tool results is the harness
            # feeding output back, not the human speaking. Label it honestly so
            # the outside reader can tell who actually said what.
            if role == "user" and isinstance(content, list) and content and all(
                isinstance(b, dict) and b.get("type") in ("tool_result", "image")
                for b in content
            ):
                role = "tool"

            parts: list[str] = []
            if isinstance(content, str):
                parts.append(content)
            elif isinstance(content, list):
                for block in content:
                    if isinstance(block, dict) and block.get("type") == "thinking":
                        if keep_thinking:
                            think = block.get("thinking", "")
                            if think.strip():
                                parts.append(f"[thinking] {think}")
                        continue
                    rendered = block_text(block)
                    if rendered.strip():
                        parts.append(rendered)

            text = "\n".join(p for p in parts if p.strip()).strip()
            if not text:
                continue

            # Claude Code's own injected reminders are noise to an outside reader.
            if role in ("user", "tool") and text.startswith("<system-reminder>") and text.endswith("</system-reminder>"):
                continue
            text = re.sub(r"<system-reminder>.*?</system-reminder>", "", text, flags=re.S).strip()
            if not text:
                continue

            # A previous freshair run whose payload was logged into this session.
            # Treating it as a human instruction would make each review the
            # input to the next one.
            if FRESHAIR_MARKER in text or any(sig in text for sig in LEGACY_SIGNATURES):
                continue

            turns.append({"role": role, "text": text, "ts": rec.get("timestamp", "")})

    return turns


# --------------------------------------------------------------------------
# shaping it to fit
# --------------------------------------------------------------------------

def render_turns(turns: list[dict]) -> str:
    out = []
    for i, t in enumerate(turns, 1):
        who = {"user": "HUMAN", "assistant": "AGENT"}.get(t["role"], "TOOL OUTPUT")
        out.append(f"--- turn {i} · {who} ---\n{t['text']}")
    return "\n\n".join(out)


def fit_to_budget(turns: list[dict], budget: int, head_turns: int) -> tuple[str, dict]:
    """
    Keep the opening turns (the original goal — the single most important thing
    for spotting drift) and as many recent turns as fit. Elide the middle.
    """
    stats = {"total_turns": len(turns), "kept_turns": len(turns), "elided_turns": 0}

    full = render_turns(turns)
    if len(full) <= budget:
        return full, stats

    head = turns[:head_turns]
    head_text = render_turns(head)
    if len(head_text) > budget:
        # Pathological case: the opening turns alone blow the budget. Keep the
        # original ask visible rather than dropping it.
        stats["kept_turns"] = len(head)
        stats["elided_turns"] = len(turns) - len(head)
        return clip(head_text, budget), stats

    tail: list[dict] = []
    used = len(head_text)
    for t in reversed(turns[head_turns:]):
        chunk = len(t["text"]) + 40
        if used + chunk > budget:
            break
        tail.append(t)
        used += chunk
    tail.reverse()

    elided = len(turns) - len(head) - len(tail)
    stats["kept_turns"] = len(head) + len(tail)
    stats["elided_turns"] = elided

    gap = (
        f"\n\n--- [{elided} turns from the middle of the session were elided to fit; "
        f"the opening and the most recent work are both intact] ---\n\n"
    )
    return head_text + gap + render_turns(tail), stats


GOAL_TURN_CAP = 6_000
CLAIM_CAP = 4_000


# Continuations the harness injects as user turns. They carry no requirement,
# and listing them as goals dilutes the real ones.
BOILERPLATE = {
    "continue from where you left off.",
    "continue",
    "continue.",
    "go on",
    "keep going",
    "please continue",
}


# Harness notices delivered as user turns — "[Request interrupted by user]" and
# friends. They report on the session, they do not ask for anything.
HARNESS_NOTICE = re.compile(r"^\[[^\]\n]{0,120}\]$")


def goal_instructions(turns: list[dict], goal_turns: int) -> list[str]:
    """What the human actually asked for, and nothing the agent said back.

    The human's messages are the requirements. The agent's are where the
    rationalization lives, which is the whole thing we are trying not to ship.
    """
    texts = []
    for turn in turns:
        if turn["role"] != "user":
            continue
        text = turn["text"].strip()
        if not text or text.lower() in BOILERPLATE or HARNESS_NOTICE.match(text):
            continue
        # An instruction cut off mid-send and retyped supersedes the fragment it
        # extends; listing both reads as two separate requirements.
        if texts and text.startswith(texts[-1]):
            texts[-1] = text
        else:
            texts.append(text)
    return texts[:goal_turns] if goal_turns > 0 else texts


def extract_goal(turns: list[dict], goal_turns: int) -> str:
    kept = goal_instructions(turns, goal_turns)
    if not kept:
        return "(no human instructions found in this session)"
    return "\n\n".join(
        f"--- instruction {i} ---\n{clip(text, GOAL_TURN_CAP)}"
        for i, text in enumerate(kept, 1)
    )


def extract_claim(turns: list[dict]) -> str:
    """The agent's most recent account of where things stand.

    Included as a claim to be checked against the diff, not as evidence. Tool
    invocations are stripped — what is wanted is the self-report, not the log.
    """
    for turn in reversed(turns):
        if turn["role"] != "assistant":
            continue
        prose = [ln for ln in turn["text"].splitlines()
                 if not ln.startswith("[tool")]
        text = "\n".join(prose).strip()
        if text:
            return clip(text, CLAIM_CAP)
    return ""


SECRET_PATTERNS = [
    (re.compile(r"sk-or-v1-[A-Za-z0-9]{16,}"), "sk-or-v1-***REDACTED***"),
    (re.compile(r"sk-ant-[A-Za-z0-9\-_]{16,}"), "sk-ant-***REDACTED***"),
    (re.compile(r"sk-proj-[A-Za-z0-9\-_]{16,}"), "sk-proj-***REDACTED***"),
    (re.compile(r"\bsk-[A-Za-z0-9]{32,}"), "sk-***REDACTED***"),
    (re.compile(r"gh[pousr]_[A-Za-z0-9]{20,}"), "gh*_***REDACTED***"),
    (re.compile(r"AKIA[0-9A-Z]{16}"), "AKIA***REDACTED***"),
    (re.compile(r"AIza[0-9A-Za-z\-_]{30,}"), "AIza***REDACTED***"),
    (re.compile(r"xox[baprs]-[A-Za-z0-9\-]{10,}"), "xox*-***REDACTED***"),
    (re.compile(r"ey[A-Za-z0-9_\-]{10,}\.[A-Za-z0-9_\-]{10,}\.[A-Za-z0-9_\-]{10,}"), "***JWT-REDACTED***"),
    (re.compile(r"-----BEGIN [A-Z ]*PRIVATE KEY-----.*?-----END [A-Z ]*PRIVATE KEY-----", re.S), "***PRIVATE-KEY-REDACTED***"),
]


def redact(text: str) -> tuple[str, int]:
    count = 0
    for pattern, replacement in SECRET_PATTERNS:
        text, n = pattern.subn(replacement, text)
        count += n
    return text, count


# --------------------------------------------------------------------------
# repo context
# --------------------------------------------------------------------------

def git(args: list[str], cwd: Path) -> str:
    try:
        r = subprocess.run(
            ["git"] + args, cwd=cwd, capture_output=True, text=True, timeout=20
        )
        return r.stdout if r.returncode == 0 else ""
    except (OSError, subprocess.SubprocessError):
        return ""


def branch_base(cwd: Path) -> tuple[str, str]:
    """The ref this branch forked from, and the commit where it forked.

    Used when the working tree is clean: the work still exists, it is just
    committed, and a reviewer with no diff at all has nothing to judge.
    """
    head = git(["rev-parse", "--abbrev-ref", "HEAD"], cwd).strip()
    candidates = []

    resolved = git(["symbolic-ref", "--short", "refs/remotes/origin/HEAD"], cwd).strip()
    if resolved:
        candidates.append(resolved)
    candidates += ["origin/main", "origin/master", "main", "master"]

    for name in candidates:
        if name == head or name.endswith("/" + head):
            continue  # a branch cannot be diffed against itself
        if not git(["rev-parse", "--verify", "--quiet", name], cwd).strip():
            continue
        base = git(["merge-base", "HEAD", name], cwd).strip()
        if base:
            return name, base
    return "", ""


def repo_context(cwd: Path) -> tuple[str, str]:
    """Returns (summary_block, diff_block)."""
    if git(["rev-parse", "--is-inside-work-tree"], cwd).strip() != "true":
        return "", ""

    branch = git(["rev-parse", "--abbrev-ref", "HEAD"], cwd).strip()
    status = git(["status", "--short"], cwd).strip()
    log = git(["log", "--oneline", "-8"], cwd).strip()

    summary = "===== REPO STATE =====\n"
    if branch:
        summary += f"branch: {branch}\n"
    if log:
        summary += f"\nrecent commits:\n{log}\n"
    if status:
        summary += f"\nworking tree:\n{status}\n"
    summary += "======================\n\n"

    diff = git(["diff", "HEAD"], cwd)
    title = "UNCOMMITTED DIFF (the work under review)"

    if not diff.strip():
        diff = git(["diff"], cwd)

    if not diff.strip():
        # Clean tree. The work is committed, not absent — right after a commit
        # is exactly when a second opinion is worth asking for.
        ref, base = branch_base(cwd)
        if base:
            diff = git(["diff", base, "HEAD"], cwd)
            title = f"EVERYTHING THIS BRANCH CHANGED vs {ref} (the work under review)"

    if not diff.strip():
        return summary, ""

    diff_block = (
        f"\n===== {title} =====\n"
        + clip(diff, DIFF_CAP)
        + "\n===== END DIFF =====\n"
    )
    return summary, diff_block


# --------------------------------------------------------------------------
# calling OpenRouter
# --------------------------------------------------------------------------

def ask_openrouter(model: str, system: str, user: str, api_key: str,
                   temperature: float, timeout: int) -> dict:
    payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": system},
            {"role": "user", "content": user},
        ],
        "temperature": temperature,
    }
    req = urllib.request.Request(
        OPENROUTER_URL,
        data=json.dumps(payload).encode("utf-8"),
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
            # OpenRouter shows these on the user's activity page. The referer
            # is the repository, which is still named what-do-you-think; the
            # title is the tool.
            "HTTP-Referer": "https://github.com/jiaazhaoo/what-do-you-think",
            "X-Title": "FreshAir",
        },
        method="POST",
    )

    started = time.time()
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            body = json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as e:
        detail = e.read().decode("utf-8", "replace")[:600]
        return {"model": model, "error": f"HTTP {e.code}: {detail}"}
    except Exception as e:  # noqa: BLE001 — surface anything the network does
        return {"model": model, "error": f"{type(e).__name__}: {e}"}

    choices = body.get("choices") or []
    if not choices:
        return {"model": model, "error": f"no choices in response: {json.dumps(body)[:600]}"}

    return {
        "model": model,
        "text": (choices[0].get("message") or {}).get("content", "").strip(),
        "usage": body.get("usage") or {},
        "seconds": round(time.time() - started, 1),
    }


# --------------------------------------------------------------------------
# calling a locally installed, already-signed-in vendor CLI
# --------------------------------------------------------------------------

def cli_command(spec: dict, model: str | None, repo: Path | None = None) -> list[str]:
    """Flags first, then the model, then whatever must stay last — a stdin
    sentinel or a variadic list that would otherwise swallow what follows."""
    cmd = list(spec["cmd"])
    if repo and spec.get("dir_flag"):
        cmd += [spec["dir_flag"], str(repo)]
    if model and spec.get("model_flag"):
        cmd += [spec["model_flag"], model]
    return cmd + list(spec.get("tail") or [])


# Variables that tell a nested agent CLI which session it belongs to. Leaving
# them set makes the child append its own prompt to *this* session's transcript,
# which is the file we are reviewing. Auth-bearing variables are deliberately
# left alone.
CHILD_ENV_STRIP = (
    "CLAUDE_CODE_SESSION_ID",
    "CLAUDE_SESSION_ID",
    "CLAUDE_CODE_CHILD_SESSION",
    "CLAUDE_PROJECT_DIR",
    "CLAUDE_CODE_ENTRYPOINT",
    "CLAUDE_AFTER_LAST_COMPACT",
    "CLAUDE_CODE_DIAGNOSTICS_FILE",
)


def child_env() -> dict:
    env = dict(os.environ)
    for key in CHILD_ENV_STRIP:
        env.pop(key, None)
    return env


def ask_cli(backend: str, spec: dict, model: str | None, system: str, user: str,
            timeout: int, repo: Path) -> dict:
    """Run the reviewer outside the repository.

    An agent CLI files its session log under a directory derived from its
    working directory. Started inside the repo, the reviewer's own prompt lands
    in the very transcript we read — so the next review takes the last review as
    input. Running it from a scratch directory puts that log somewhere harmless,
    and `dir_flag` hands the repo back as readable.
    """
    cmd = cli_command(spec, model, repo)
    name = f"{backend}" + (f" · {model}" if model else "")

    started = time.time()
    try:
        with tempfile.TemporaryDirectory(prefix="freshair-") as scratch:
            proc = subprocess.run(
                cmd,
                input=f"{system}\n\n{user}",
                capture_output=True,
                text=True,
                timeout=timeout,
                cwd=scratch,
                env=child_env(),
            )
    except FileNotFoundError:
        return {"model": name, "error": f"{spec['cmd'][0]} is not installed or not on PATH"}
    except subprocess.TimeoutExpired:
        return {"model": name, "error": f"timed out after {timeout}s"}
    except OSError as e:
        return {"model": name, "error": f"{type(e).__name__}: {e}"}

    out = (proc.stdout or "").strip()
    if proc.returncode != 0 and not out:
        err = (proc.stderr or "").strip()[:800] or f"exit code {proc.returncode}"
        return {
            "model": name,
            "error": f"{' '.join(cmd)}\n{err}\n\n"
                     f"If this backend's flags have changed upstream, override "
                     f"them in .freshair.json under backends.{backend}.cmd",
        }
    if not out:
        return {"model": name, "error": f"{' '.join(cmd)} produced no output"}

    return {"model": name, "text": out, "usage": {}, "seconds": round(time.time() - started, 1)}


PROBE_PROMPT = "Reply with exactly this token and nothing else: FRESHAIR-OK"
PROBE_TOKEN = "FRESHAIR-OK"


def check_backends(backends: dict[str, dict], selected: list[str],
                   config: dict, timeout: int, repo: Path) -> int:
    """Actually call each backend with a one-token prompt.

    The command lines here are built from each vendor's documented flags, and
    vendors change flags. This turns "should work" into something the user can
    confirm on their own machine in a few seconds.
    """
    failures = 0

    # The in-progress line only makes sense on a terminal; carriage returns do
    # not overwrite anything in a pipe or a log file.
    live = sys.stdout.isatty()

    def progress(line: str) -> None:
        if live:
            print(line, end="\r", flush=True)

    def emit(line: str) -> None:
        print(("\r" + " " * 60 + "\r" if live else "") + line)

    for name in selected:
        if name == "openrouter":
            key = os.environ.get("OPENROUTER_API_KEY", "").strip()
            if not key:
                emit("  ✗ openrouter — OPENROUTER_API_KEY is not set")
                failures += 1
                continue
            model = (config.get("models") or DEFAULT_MODELS)[0]
            progress(f"  … openrouter ({model})")
            r = ask_openrouter(model, "", PROBE_PROMPT, key, 0.0, timeout)
            label = f"openrouter ({model})"
        else:
            spec = backends[name]
            binary = spec["cmd"][0]
            if not shutil.which(binary):
                emit(f"  – {name:<11} not installed ({binary} not on PATH)")
                continue
            cmd = " ".join(cli_command(spec, None, repo))
            progress(f"  … {name}")
            r = ask_cli(name, spec, None, "", PROBE_PROMPT, timeout, repo)
            label = f"{name:<11} {cmd}"

        if r.get("error"):
            emit(f"  ✗ {label}\n      {r['error'].splitlines()[0]}")
            failures += 1
        elif PROBE_TOKEN not in (r.get("text") or ""):
            emit(f"  ✗ {label}\n      responded, but not with the probe token: "
                 f"{(r.get('text') or '')[:120]!r}")
            failures += 1
        else:
            emit(f"  ✓ {label}   ({r['seconds']}s)")

    return failures


def resolve_backends(config: dict) -> dict[str, dict]:
    """Built-in CLI backends, with per-repo overrides layered on top."""
    merged = {k: dict(v) for k, v in CLI_BACKENDS.items()}
    for name, override in (config.get("backends") or {}).items():
        merged.setdefault(name, {"label": name, "vendor": name})
        merged[name].update(override)
    return merged


def detect_backend(backends: dict[str, dict]) -> str:
    """Pick a backend the user is already signed in to, outsiders first."""
    order = [b for b in AUTO_ORDER if b in backends]
    order += [b for b in backends if b not in order]

    non_anthropic = [b for b in order if backends[b].get("vendor") != "anthropic"]
    for name in non_anthropic:
        if shutil.which(backends[name]["cmd"][0]):
            return name

    if os.environ.get("OPENROUTER_API_KEY", "").strip():
        return "openrouter"

    for name in order:
        if shutil.which(backends[name]["cmd"][0]):
            return name

    return "openrouter"


# --------------------------------------------------------------------------

def die(msg: str) -> None:
    print(f"freshair: {msg}", file=sys.stderr)
    sys.exit(1)


def load_config(cwd: Path) -> dict:
    for path in (cwd / ".freshair.json",
                 Path.home() / ".config" / "freshair" / "config.json",
                 cwd / ".wdyt.json",                              # pre-rename names
                 Path.home() / ".config" / "wdyt" / "config.json"):
        if path.is_file():
            try:
                return json.loads(path.read_text(encoding="utf-8"))
            except json.JSONDecodeError:
                print(f"freshair: ignoring malformed config at {path}", file=sys.stderr)
    return {}


def main() -> None:
    cwd = Path(os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd()).resolve()
    config = load_config(cwd)
    backends = resolve_backends(config)

    ap = argparse.ArgumentParser(
        prog="freshair",
        description="FreshAir — get an outside opinion from a model that has "
                    "not seen this conversation.",
    )
    ap.add_argument("focus", nargs="*",
                    help="what to look at, e.g. 'is the caching layer worth it'")
    ap.add_argument("--mode", choices=["fresh", "full"],
                    default=config.get("mode", "fresh"),
                    help="fresh (default): send only the goal and the current "
                         "state, so the reviewer cannot be anchored by the "
                         "reasoning that got you here. full: send the whole "
                         "transcript, for 'where exactly did we go wrong'.")
    ap.add_argument("--goal-turns", type=int, default=int(config.get("goal_turns", 0)),
                    help="in fresh mode, use only the first N human "
                         "instructions as the goal (0 = all of them)")
    ap.add_argument("-b", "--backend",
                    default=config.get("backend", "auto"),
                    help="auto (default) | " + " | ".join(list(backends) + ["openrouter"])
                         + ". CLI backends use the login you already have; "
                           "openrouter needs OPENROUTER_API_KEY.")
    ap.add_argument("-m", "--model", action="append", default=[],
                    help="model id; repeat or comma-separate to run several in "
                         "parallel. Omit on a CLI backend to use its own default.")
    ap.add_argument("--transcript", help="path to a session .jsonl (default: this session)")
    ap.add_argument("--session-id", help="session id to look up, if autodetection picks wrong")
    ap.add_argument("--budget", type=int,
                    default=int(config.get("budget", DEFAULT_BUDGET)),
                    help=f"max transcript characters to send (default {DEFAULT_BUDGET})")
    ap.add_argument("--head-turns", type=int, default=int(config.get("head_turns", 6)),
                    help="opening turns always kept, so drift stays visible (default 6)")
    ap.add_argument("--thinking", action="store_true",
                    help="include the agent's thinking blocks")
    ap.add_argument("--no-diff", action="store_true", help="do not attach the git diff")
    ap.add_argument("--no-claim", action="store_true",
                    help="in fresh mode, withhold the agent's own account of "
                         "where things stand, leaving only the goal and the diff")
    ap.add_argument("--no-redact", action="store_true",
                    help="skip the credential scrub (not recommended)")
    ap.add_argument("--lang", default=config.get("lang", "the language the human used in the transcript"),
                    help="language for the review")
    ap.add_argument("--temperature", type=float, default=float(config.get("temperature", 0.7)))
    ap.add_argument("--timeout", type=int, default=int(config.get("timeout", 600)))
    ap.add_argument("--check", action="store_true",
                    help="probe each backend with a one-token prompt and report "
                         "which ones actually work on this machine")
    ap.add_argument("--dry-run", action="store_true",
                    help="print exactly what would be sent and how, call nothing")
    ap.add_argument("--save", metavar="PATH", help="also write the review to this file")
    args = ap.parse_args()

    if args.check:
        selected = ([args.backend] if args.backend not in ("auto", None)
                    else list(backends) + ["openrouter"])
        print("Probing backends (a real call each, one token of output):")
        sys.exit(1 if check_backends(backends, selected, config, args.timeout, cwd) else 0)

    backend = args.backend
    if backend == "auto":
        backend = detect_backend(backends)
    if backend != "openrouter" and backend not in backends:
        die(f"unknown backend {backend!r}. Known: "
            + ", ".join(list(backends) + ["openrouter", "auto"]))

    is_cli = backend != "openrouter"

    models: list[str | None] = []
    for entry in args.model:
        models.extend(m.strip() for m in entry.split(",") if m.strip())
    if not models:
        if is_cli:
            configured = backends[backend].get("models") or []
            models = list(configured) or [None]   # None = let the CLI choose
        else:
            models = list(config.get("models") or DEFAULT_MODELS)

    # ---- build the payload ------------------------------------------------
    path = find_transcript(args.transcript, cwd, args.session_id)
    turns = parse_transcript(path, keep_thinking=args.thinking)
    if not turns:
        die(f"no readable turns in {path}")

    repo_block, diff_block = ("", "")
    if not args.no_diff:
        repo_block, diff_block = repo_context(cwd)

    focus_block = ""
    focus = " ".join(args.focus).strip()
    if focus:
        focus_block = f"The human specifically wants your read on: {focus}\n\n"

    verify_rule = VERIFY_RULE_CLI if is_cli else VERIFY_RULE_API

    if args.mode == "fresh":
        goal = extract_goal(turns, args.goal_turns)
        claim = "" if args.no_claim else extract_claim(turns)
        claim_block = ""
        if claim:
            claim_block = (
                "\n===== THE AGENT'S OWN ACCOUNT OF WHERE THIS STANDS =====\n"
                "(A claim, not evidence. Check it against the diff above.)\n\n"
                f"{claim}\n"
                "===== END ACCOUNT =====\n"
            )
        if not diff_block and not repo_block:
            claim_block += (
                "\n(No git repository here, so there is no diff to check the "
                "account against.)\n"
            )

        system_msg = SYSTEM_PROMPT_FRESH.format(verify_rule=verify_rule)
        user_msg = USER_TEMPLATE_FRESH.format(
            focus_block=focus_block,
            goal=goal,
            repo_block=repo_block,
            diff_block=diff_block,
            claim_block=claim_block,
            lang=args.lang,
        )
        shown = len(goal_instructions(turns, args.goal_turns))
        stats = {"total_turns": len(turns), "kept_turns": shown,
                 "elided_turns": len(turns) - shown}
        shape = (f"goal: {shown} human instruction(s) + current state; "
                 f"{len(turns) - shown} turns of agent reasoning withheld")
    else:
        transcript, stats = fit_to_budget(turns, args.budget, args.head_turns)
        system_msg = SYSTEM_PROMPT_FULL.format(verify_rule=verify_rule)
        user_msg = USER_TEMPLATE_FULL.format(
            focus_block=focus_block,
            repo_block=repo_block,
            transcript=transcript,
            diff_block=diff_block,
            lang=args.lang,
        )
        shape = (f"turns: {stats['kept_turns']}/{stats['total_turns']} kept"
                 + (f", {stats['elided_turns']} elided from the middle"
                    if stats["elided_turns"] else ""))

    redacted_count = 0
    if not args.no_redact:
        user_msg, redacted_count = redact(user_msg)

    if is_cli:
        route = (f"{backends[backend].get('label', backend)} — local CLI, "
                 f"your own login, nothing routed through a third party")
    else:
        route = "OpenRouter API"

    same_vendor = is_cli and HOST_VENDOR and backends[backend].get("vendor") == HOST_VENDOR
    warning = ""
    if same_vendor:
        warning = (
            f"\n⚠️  {backend} is the same vendor as the agent you are already "
            "talking to. A fresh context window helps, but shared weights mean "
            "shared blind spots — this is the weak version of a second opinion.\n"
            "    For a real outsider: install and sign in to codex or gemini, "
            "or use --backend openrouter.\n"
        )

    header = (
        f"transcript: {path}\n"
        f"mode: {args.mode}\n"
        f"{shape}\n"
        f"payload: {len(user_msg):,} chars (~{len(user_msg)//4:,} tokens)\n"
        f"backend: {route}\n"
        f"models: {', '.join(m or '(backend default)' for m in models)}\n"
        + (f"redacted: {redacted_count} credential-shaped strings\n" if redacted_count else "")
        + warning
    )

    if args.dry_run:
        print(header)
        if is_cli:
            for m in models:
                print("would run: " + " ".join(cli_command(backends[backend], m, cwd))
                      + "\n           (prompt on stdin, from a scratch cwd)")
            print()
        print("=" * 70)
        print("SYSTEM:\n" + system_msg)
        print("=" * 70)
        print("USER:\n" + user_msg)
        return

    # ---- dispatch ---------------------------------------------------------
    if is_cli:
        binary = backends[backend]["cmd"][0]
        if not shutil.which(binary):
            die(f"backend {backend!r} needs {binary!r} on PATH, and it is not there.\n"
                f"Install and sign in to it, pick another with --backend, "
                f"or use --backend openrouter.")
        run = lambda m: ask_cli(backend, backends[backend], m, system_msg,  # noqa: E731
                                user_msg, args.timeout, cwd)
    else:
        api_key = os.environ.get("OPENROUTER_API_KEY", "").strip()
        if not api_key:
            die("OPENROUTER_API_KEY is not set. Either get a key at "
                "https://openrouter.ai/keys, or use a CLI you are already signed "
                "in to: --backend codex | gemini | claude")
        run = lambda m: ask_openrouter(m, system_msg, user_msg, api_key,  # noqa: E731
                                       args.temperature, args.timeout)

    print(header, file=sys.stderr)

    with concurrent.futures.ThreadPoolExecutor(max_workers=max(1, len(models))) as pool:
        results = list(pool.map(run, models))

    # ---- report -----------------------------------------------------------
    chunks = [f"# 外部意见 / Outside opinion\n\n_{datetime.now(timezone.utc).astimezone():%Y-%m-%d %H:%M} · via {route}_\n"]
    failures = 0
    for r in results:
        if r.get("error"):
            failures += 1
            chunks.append(f"\n---\n\n## ❌ {r['model']}\n\n```\n{r['error']}\n```\n")
            continue
        usage = r.get("usage") or {}
        meta = f"{r['seconds']}s"
        if usage.get("total_tokens"):
            meta += f" · {usage['total_tokens']:,} tokens"
        chunks.append(f"\n---\n\n## 🔎 {r['model']}\n\n_{meta}_\n\n{r['text']}\n")

    out = "".join(chunks)
    print(out)

    if args.save:
        Path(args.save).expanduser().write_text(out, encoding="utf-8")
        print(f"\nsaved to {args.save}", file=sys.stderr)

    if failures == len(results):
        sys.exit(1)


if __name__ == "__main__":
    main()
